---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: Você pode gerenciar a segurança no SnapManager aplicando autenticação de usuário. O método de autenticação de usuário permite acessar recursos como repositórios, hosts e perfis. 
---
= Gerenciamento de segurança e credenciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar a segurança no SnapManager aplicando autenticação de usuário. O método de autenticação de usuário permite acessar recursos como repositórios, hosts e perfis.

Quando você executa uma operação usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI), o SnapManager recupera as credenciais definidas para repositórios e perfis. O SnapManager salva credenciais de instalações anteriores.

O repositório e os perfis podem ser protegidos com uma senha. Uma credencial é a senha configurada para o usuário para um objeto e a senha não está configurada no próprio objeto.

Você pode gerenciar autenticação e credenciais executando as seguintes tarefas:

* Gerencie a autenticação do usuário por meio de prompts de senha em operações ou usando o `smsap credential set` comando.
+
Defina credenciais para um repositório, host ou perfil.

* Exibir as credenciais que regem os recursos aos quais você tem acesso.
* Limpe as credenciais de um usuário para todos os recursos (hosts, repositórios e perfis).
* Exclua as credenciais de um usuário para recursos individuais (hosts, repositórios e perfis).



NOTE: Se o banco de dados do repositório estiver em um host do Windows, o usuário local ou administrador e o usuário do domínio devem ter as mesmas credenciais.
