---
permalink: windows/concept-accessing-snapmanager.html 
sidebar: sidebar 
keywords: access, snapmanager, command-line, interface, cli, graphical, user, interface, gui 
summary: 'Você pode acessar o SnapManager usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI).' 
---
= Acessando o SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar o SnapManager usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI).

Você pode executar diferentes operações do SnapManager das seguintes maneiras:

* Ao inserir comandos na CLI em um host que está na mesma rede que o host do banco de dados.
+
Para obter uma lista de todos os comandos e uma explicação de suas opções e argumentos, consulte o capítulo Referência de comando.

+
Para acessar a CLI, clique em *Iniciar* > *todos os programas* > *NetApp* > *SnapManager para SAP* > *Iniciar a interface de linha de comando (CLI) do SMSAP*.

* Acessando a GUI em um host na mesma rede que o host do banco de dados.
+
A GUI fornece assistentes simples e fáceis de usar para ajudar você a realizar operações diferentes.

* Usando comandos SAP BR*Tools.

