---
permalink: windows/concept-cloning-database-backup.html 
sidebar: sidebar 
keywords: clone, database, task, test, upgrade, affect, production, duplicate, master, installation, train, system, duplicate, master, base, server, requirement, clone 
summary: Se você clonar um banco de dados, poderá executar tarefas como testar uma atualização para um banco de dados sem afetar o banco de dados em produção, duplicar uma instalação mestre para vários sistemas de treinamento ou duplicar uma instalação mestre como uma instalação base para outros servidores, que têm requisitos semelhantes. 
---
= Clonagem do backup do banco de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você clonar um banco de dados, poderá executar tarefas como testar uma atualização para um banco de dados sem afetar o banco de dados em produção, duplicar uma instalação mestre para vários sistemas de treinamento ou duplicar uma instalação mestre como uma instalação base para outros servidores, que têm requisitos semelhantes.

Você pode executar as seguintes tarefas relacionadas à clonagem:

* Clonar um banco de dados a partir de um backup existente.
* Clonar um banco de dados em seu estado atual, o que permite criar o backup e o clone em um procedimento.
* Clonar um banco de dados e usar scripts de plug-in personalizados, que são executados antes ou depois da operação de clone.
* Clonar um banco de dados para o mesmo host no qual o banco de dados reside.
* Clonar um banco de dados usando arquivos de log de arquivamento do local de log de arquivamento externo.
* Clonar um banco de dados para um host alternativo.
* Exibir uma lista de clones.
* Veja informações detalhadas sobre clones.
* Excluir clones.

