---
permalink: windows/concept-variables-available-in-the-task-scripts-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, provide, context, information, environment, variable, relate, backup, operation, perform, example, original, host, retention, policy, label, script 
summary: O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de backup que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original, o nome da política de retenção e o rótulo do backup. 
---
= Variáveis disponíveis nos scripts de tarefa para a operação de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de backup que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original, o nome da política de retenção e o rótulo do backup.

A tabela a seguir lista as variáveis de ambiente que você pode usar em seus scripts:

|===
| Variáveis | Descrição | Formato 


 a| 
`_SM_OPERATION_ID_`
 a| 
Especifica o ID da operação atual
 a| 
cadeia de carateres



 a| 
`_SM_PROFILE_NAME_`
 a| 
Especifica o nome do perfil usado
 a| 
cadeia de carateres



 a| 
`_SM_SID_`
 a| 
Especifica o identificador do sistema do banco de dados
 a| 
cadeia de carateres



 a| 
`_SM_HOST_`
 a| 
Especifica o nome do host do banco de dados
 a| 
cadeia de carateres



 a| 
`_SM_OS_USER_`
 a| 
Especifica o proprietário do sistema operacional (SO) do banco de dados
 a| 
cadeia de carateres



 a| 
`_SM_OS_GROUP_`
 a| 
Especifica o grupo de SO do banco de dados
 a| 
cadeia de carateres



 a| 
`_SM_BACKUP_TYPE_`
 a| 
Especifica o tipo de backup (on-line, off-line ou automático)
 a| 
cadeia de carateres



 a| 
`_SM_BACKUP_LABEL_`
 a| 
Especifica o rótulo do backup
 a| 
cadeia de carateres



 a| 
`_SM_BACKUP_ID_`
 a| 
Especifica a ID do backup
 a| 
cadeia de carateres



 a| 
`_SM_BACKUP_RETENTION_`
 a| 
Especifica o período de retenção
 a| 
cadeia de carateres



 a| 
`_SM_BACKUP_PROFILE_`
 a| 
Especifica o perfil usado para esse backup
 a| 
cadeia de carateres



 a| 
`_SM_ALLOW_DATABASE_SHUTDOWN_`
 a| 
Especifica se você deseja iniciar ou encerrar o banco de dados se necessário, você pode usar a opção -force da interface de linha de comando.
 a| 
booleano



 a| 
`_SM_BACKUP_SCOPE_`
 a| 
Especifica o escopo do backup (total ou parcial)
 a| 
cadeia de carateres



 a| 
`_SM_TARGET_FILER_NAME_`
 a| 
Especifica o nome do sistema de armazenamento de destino

[NOTE]
====
Se mais de um sistema de armazenamento for usado, os nomes do sistema de armazenamento devem ser separados por vírgulas.

==== a| 
cadeia de carateres



 a| 
`_SM_TARGET_VOLUME_NAME_`
 a| 
Especifica o nome do volume de destino

[NOTE]
====
O nome do volume de destino deve ser prefixado com o nome do dispositivo de armazenamento, por exemplo, SM_TARGET_ARQUIVADOR_name/SM_TARGET_VOLUME_NAME.

==== a| 
cadeia de carateres



 a| 
`_SM_HOST_FILE_SYSTEM_`
 a| 
Especifica o sistema de arquivos host
 a| 
cadeia de carateres



 a| 
`_SM_SNAPSHOT_NAMES_`
 a| 
Especifica a lista Snapshot (Instantâneo)

[NOTE]
====
O nome das cópias Snapshot deve ser pré-fixado com o nome do sistema de storage e o nome do volume. Os nomes das cópias Snapshot são separados por vírgulas.

==== a| 
array de cadeia de carateres



 a| 
`_SM_ARCHIVE_LOGS_DIRECTORY_`
 a| 
Especifica o diretório de logs de arquivo

[NOTE]
====
Se os logs do arquivo estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.

==== a| 
array de cadeia de carateres



 a| 
`_SM_REDO_LOGS_DIRECTORY_`
 a| 
Especifica o diretório refazer logs

[NOTE]
====
Se os logs de refazer estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.

==== a| 
array de cadeia de carateres



 a| 
`_SM_CONTROL_FILES_DIRECTORY_`
 a| 
Especifica o diretório de arquivos de controle

[NOTE]
====
Se os arquivos de controle estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.

==== a| 
array de cadeia de carateres



 a| 
`_SM_DATA_FILES_DIRECTORY_`
 a| 
Especifica o diretório de arquivos de dados

[NOTE]
====
Se os arquivos de dados estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.

==== a| 
array de cadeia de carateres



 a| 
`_user_defined_`
 a| 
Especifica parâmetros adicionais definidos pelo usuário. Os parâmetros definidos pelo usuário não estão disponíveis para plug-ins usados como políticas.
 a| 
definido pelo utilizador

|===