---
permalink: windows/reference-the-smosmsapbackup-show-command.html 
sidebar: sidebar 
keywords: backup, show, command, display, detail, information, protection, status, retention, class, primary, secondary, storage, smsap 
summary: Você pode usar o comando backup show para exibir informações detalhadas sobre um backup, incluindo seu status de proteção, classe de retenção de backup e backups em storage primário e secundário. 
---
= O comando smsap backup show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `backup show` comando para exibir informações detalhadas sobre um backup, incluindo seu status de proteção, classe de retenção de backup e backups em storage primário e secundário.



== Sintaxe

[listing]
----

smsap backup show
-profile profile_name
[-label label [-data | -archivelogs] | [-id id]
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_name_`*
+
Especifica o perfil para o qual mostrar backups. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *`-label _label_`*
+
Especifica o rótulo do backup.

* *`-data`*
+
Especifica os arquivos de dados.

* *`-archivelogs`*
+
Especifica os arquivos de log de arquivamento.

* *`-id _id_`*
+
Especifica o ID de backup.

* *`-quiet`*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
Exibe mensagens de erro, aviso e informativas no console, bem como qualquer clone e informação de verificação.





== Exemplo

O exemplo a seguir mostra informações detalhadas sobre o backup:

[listing]
----
smsap backup show -profile SALES1 -label BTNFS -verbose
Backup id: 8abc013111a450480111a45066210001
Backup status: SUCCESS
Primary storage resources: EXISTS
Protection sate: NOT REQUESTED
Retention class: DAILY
Backup scope: FULL
Backup mode: OFFLINE
Mount status: NOT MOUNTED
Backup label: BTNFS
Backup comment:

Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Verification status: OK
Backup Retention Policy: NORMAL
Backup database: hsdb1
Checkpoint: 2700620
Tablespace: SYSAUX
Datafile: E:\disks\data\hsdb\sysaux01.dbf [ONLINE]
...
Control Files:
File: E:\disks\data\control03.ctl
...
Archive Logs:
File: E:\disks\data\archive_logs\2_131_626174106.dbf
...
Volume: hs_data
Snapshot: SMSAP_HSDBR_hsdb1_F_C_1_
8abc013111a450480111a45066210001_0
File: E:\disks\data\hsdb\SMSAPBakCtl_1175283005231_0
...
----