---
permalink: windows/reference-the-smosmsapoperation-list-command.html 
sidebar: sidebar 
keywords: command, list, summary, information, operation, record, profile, smsap 
summary: Este comando lista as informações resumidas de todas as operações registradas em um perfil especificado. 
---
= O comando smsap operation list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando lista as informações resumidas de todas as operações registradas em um perfil especificado.



== Sintaxe

[listing]
----

smsap operation list
-profile profile_name
[-delimiter character]
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_name_`*
+
Especifica o nome do perfil. Esse nome pode ter até 30 carateres e deve ser único dentro do host.

* *`-delimiter _character_`*
+
(Opcional) quando este parâmetro é especificado, o comando lista cada linha em uma linha separada e os atributos nessa linha são separados pelo caractere especificado.

* *`-quiet`*
+
(Opcional) exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
(Opcional) exibe mensagens de erro, aviso e informativas no console.





== Exemplo de comando

O exemplo a seguir lista as informações resumidas de todas as operações registradas no perfil especificado.

[listing]
----
smsap operation list -profile myprofile
----
[listing]
----
Start Date Status Operation ID Type Host
-------------------- ---------- -------------------------------- ------------------ --
2007-07-16 16:03:57 SUCCESS 8abc01c813d0a1530113d0a15c5f0005 Profile Create Host3
2007-07-16 16:04:55 FAILED 8abc01c813d0a2370113d0a241230001 Backup Host3
2007-07-16 16:50:56 SUCCESS 8abc01c813d0cc580113d0cc60ad0001 Profile Update Host3
2007-07-30 15:44:30 SUCCESS 8abc01c81418a88e011418a8973e0001 Remove Backup Host3
2007-08-10 14:31:27 SUCCESS 8abc01c814510ba20114510bac320001 Backup Host3
2007-08-10 14:34:43 SUCCESS 8abc01c814510e9f0114510ea98f0001 Mount Host3
2007-08-10 14:51:59 SUCCESS 8abc01c814511e6e0114511e78d40001 Unmount Host3
----