---
permalink: windows/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, information, smsap 
summary: Você pode executar o comando de restauração de backup para restaurar backups de um banco de dados ou de uma parte de um banco de dados e, opcionalmente, recuperar as informações do banco de dados. 
---
= O comando smsap backup restore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o `backup restore` comando para restaurar backups de um banco de dados ou uma parte de um banco de dados e, em seguida, opcionalmente, recuperar as informações do banco de dados.



== Sintaxe

[listing]
----

smsap backup restore
-profile profile_name
[-label label | -id id]
[-files files [files...] |
-tablespaces tablespaces [tablespaces...]] |
-complete | -controlfiles]
[-recover {-alllogs | -nologs | -until until} [-using-backup-controlfile]]
[-restorespec restorespec | ]]
[-preview]

[-recover-from-location path1 [, path2]]
[-taskspec taskspec]
[-dump]
[-force]
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_name_`*
+
Especifica o banco de dados que você deseja restaurar. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *`-label _name_`*
+
Restaura o backup com o rótulo especificado.

* *`-id _guid_`*
+
Restaura a cópia de segurança com o GUID especificado. O GUID é gerado pelo SnapManager quando cria uma cópia de segurança. Pode utilizar o `smsap backup list` comando para apresentar o GUID para cada cópia de segurança.

* *`Choose all or specified files`*
+
Opcionalmente, você pode usar uma das seguintes opções:

+
** `-complete`: Restaura todos os arquivos de dados no backup.
** `-tablespaceslist`: Restaura apenas os espaços de tabela especificados do backup.
+
Você deve usar espaços para separar os nomes na lista.

** `-fileslist`: Restaura apenas os arquivos de dados especificados do backup.
+
Você deve usar espaços para separar os nomes na lista. Se o banco de dados estiver em execução, o SnapManager garante que o espaço de tabela que contém os arquivos esteja offline.



* *`-controlfiles`*
+
Restaura os arquivos de controle. O SnapManager permite restaurar arquivos de controle juntamente com os arquivos de dados dos backups em uma única operação. A `-controlfiles` opção é independente de outros parâmetros de escopo de restauração, como `-complete`, `-tablespaces` e `-files`.

* *`-recover`*
+
Recupera o banco de dados após restaurá-lo. Você também deve especificar o ponto para o qual deseja que o SnapManager recupere o banco de dados usando uma das seguintes opções:

+
** `-nologs`: Recupera o banco de dados até o momento do backup e não aplica logs.
+
Você pode usar este parâmetro para backups online ou offline.

** `-alllogs`: Recupera o banco de dados para a última transação ou commit, e aplica todos os logs necessários.
** `-until date`: Recupera o banco de dados até a data e hora especificadas.
+
Você deve usar o formato ano-mês-data: Hora: Minuto: Segundo (_aaaa-mm-dd:hh:mm:ss_). Para horas, use o formato de 12 horas ou 24 horas, dependendo da configuração do banco de dados.

** `-until scn`: Avança os ficheiros de dados até atingir o número de alteração do sistema (SCN) especificado.
** `-using-backup-controlfile`: Recupera o banco de dados usando o arquivo de controle de backup.


* *`-restorespec`*
+
Permite restaurar os dados para um sistema de arquivos ativo e restaurar a partir dos dados especificados fornecendo um mapeamento de cada cópia Snapshot original para o sistema de arquivos ativo. Se você não especificar uma opção, o SnapManager restaurará os dados das cópias Snapshot no storage primário. Você pode especificar uma das seguintes opções:

+
** `-restorespec`: Especifica os dados a serem restaurados e o formato de restauração.


* *`-preview`*
+
Exibe as seguintes informações:

+
** Qual mecanismo de restauração (restauração do sistema de arquivos no lado do storage, restauração de arquivos no lado do storage ou restauração de cópia de arquivo no lado do host) será usado para restaurar cada arquivo
** Por que mecanismos mais eficientes não foram usados para restaurar cada arquivo, quando você especifica a `-verbose` opção se estiver usando a `-preview` opção, você deve saber o seguinte:
** A `-force` opção não tem impactos no comando.
** A `-recover` opção não tem impactos no comando. Para visualizar a operação de restauração, o banco de dados deve ser montado. Se você quiser visualizar um plano de restauração e o banco de dados atualmente não estiver montado, o SnapManager monta o banco de dados. Se o banco de dados não puder ser montado, o comando falhará e o SnapManager retornará o banco de dados ao seu estado original.


+
A `-preview` opção exibe até 20 arquivos. Pode configurar o número máximo de ficheiros a apresentar no `smsap.config file`.

* *`-recover-from-location`*
+
Especifica a localização do log de arquivamento externo dos arquivos de log de arquivamento. O SnapManager pega os arquivos de log do arquivo do local externo e os usa para o processo de recuperação.

* *`-taskspec`*
+
Especifica o arquivo XML de especificação de tarefa para atividade de pré-processamento ou atividade de pós-processamento da operação de restauração. Você deve fornecer o caminho completo do arquivo XML de especificação de tarefa.

* *`-dump`*
+
Especifica para coletar os arquivos de despejo após a operação de restauração.

* *`-force`*
+
Altera o estado da base de dados para um estado inferior ao seu estado atual, se necessário.

+
Por padrão, o SnapManager pode alterar o estado do banco de dados para um estado mais alto durante uma operação. Esta opção não é necessária para que o SnapManager altere o banco de dados para um estado superior.

* *`-quiet`*
+
Exibe apenas mensagens de erro no console. A predefinição é apresentar mensagens de erro e aviso.

* *`-verbose`*
+
Exibe mensagens de erro, aviso e informativas no console. Você pode usar essa opção para ver por que processos de restauração mais eficientes não poderiam ser usados para restaurar o arquivo.





== Exemplo

O exemplo a seguir restaura um banco de dados juntamente com os arquivos de controle:

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----