---
permalink: windows/reference-the-smosmsap-operation-show-command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, profile, client, user, pc, smsap 
summary: 'Você pode executar o comando operation show para listar as informações resumidas de todas as operações realizadas com o perfil especificado. A saída lista o usuário cliente (o usuário para o PC cliente) e o usuário efetivo (o usuário no SnapManager que é válido no host selecionado).' 
---
= O comando smsap operation show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o `operation show` comando para listar as informações resumidas de todas as operações realizadas com o perfil especificado. A saída lista o usuário cliente (o usuário para o PC cliente) e o usuário efetivo (o usuário no SnapManager que é válido no host selecionado).



== Sintaxe

[listing]
----

smsap operation show
-profile profile_name
[-label label | -id id]
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_name_`*
+
Especifica o nome do perfil. Esse nome pode ter até 30 carateres e deve ser único dentro do host.

* *`-label _label_`*
+
Especifica o rótulo para a operação.

* *`-id _id_`*
+
Especifica o identificador para a operação.

* *`-quiet`*
+
Opcional: Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
Opcional: Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

A linha de comando a seguir mostra informações detalhadas sobre uma operação:

[listing]
----
smsap operation show -id 8ac861781d0ac992011d0ac999680001  -profile CER
----