---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: Esse comando permite definir as credenciais para que os usuários acessem recursos seguros, como hosts, repositórios e perfis de banco de dados. A senha do host é a senha do usuário no host no qual o SnapManager está sendo executado. A senha do repositório é a senha do usuário Oracle que contém o esquema do repositório SnapManager. A senha do perfil é uma senha que é composta pela pessoa que cria o perfil. Para as opções de host e repositório, se a opção opcional -password não estiver incluída, você será solicitado a digitar uma senha do tipo especificado nos argumentos de comando. 
---
= O comando smsap Credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esse comando permite definir as credenciais para que os usuários acessem recursos seguros, como hosts, repositórios e perfis de banco de dados. A senha do host é a senha do usuário no host no qual o SnapManager está sendo executado. A senha do repositório é a senha do usuário Oracle que contém o esquema do repositório SnapManager. A senha do perfil é uma senha que é composta pela pessoa que cria o perfil. Para as opções de host e repositório, se a opção opcional `-password` não estiver incluída, você será solicitado a digitar uma senha do tipo especificado nos argumentos de comando.



== Sintaxe

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== Parâmetros

* *`-host _hostname_`*
+
Especifica o nome ou endereço IP do servidor host no qual o SnapManager está sendo executado.

+
O `-host` parâmetro inclui as seguintes opções:

+
** `-name host_name`: Especifica o nome do host para o qual você definirá a senha.
** `-username user_name`: Especifica o nome de usuário no host.
** `-password password`: Especifica a senha do usuário no host.


* *`-repository -dbname`*
+
Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.

+
O `-repository` parâmetro inclui as seguintes opções:

+
** `-dbnamerepo_service_name`: Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.
** `-host repo_host`: Especifica o nome ou endereço IP do servidor host no qual o banco de dados do repositório é executado.
** `-login-username repo_username`: Especifica o nome de usuário necessário para acessar o banco de dados que armazena o repositório.
** `-password password`: Especifica a senha necessária para acessar o banco de dados que armazena o repositório.
** `-port repo_port`: Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.


* *`-profile -name _profile_name_`*
+
Especifica o perfil ao qual o banco de dados está associado.

+
O `-profile` parâmetro inclui a seguinte opção:

+
** `-name profilename`: Especifica o nome do perfil para o qual você definirá a senha.
** `-password password`: Especifica a senha necessária para acessar o perfil.


* *`-quiet`*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo de comando para definir credenciais de repositório

O exemplo a seguir define credenciais para um repositório.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Exemplo de comando para definir credenciais de host

Como uma credencial de host representa uma credencial real do sistema operacional, ela deve incluir o nome de usuário além da senha.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----