---
permalink: windows/reference-the-smosmsap-history-remove-command.html 
sidebar: sidebar 
keywords: command, enable, remove, history, snapmanager, operation, associate, single, profile, multiple, repository, smsap 
summary: Este comando permite remover o histórico de operações do SnapManager associadas a um único perfil, vários perfis ou todos os perfis em um repositório. 
---
= O comando smsap history remove
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite remover o histórico de operações do SnapManager associadas a um único perfil, vários perfis ou todos os perfis em um repositório.



== Sintaxe

[listing]
----

smsap history remove
-profile {-name profile_name [profile_name1, profile_name2] | -all
-repository
-login [-password repo_password]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation {-operations operation_name [operation_name, operation_name2] | -all}
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_`*
+
Especifica o nome do perfil. Esse nome pode ter até 30 carateres e deve ser único dentro do host.

* *`-repository`*
+
As opções que seguem -repositório especificam os detalhes do banco de dados que armazena o perfil.

* *`-dbname _repo_dbname_`*
+
Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.

* *`-host _repo_host_`*
+
Especifica o nome ou endereço IP do computador host no qual o banco de dados do repositório é executado.

* *`-login`*
+
Inicia os detalhes de login do repositório.

* *`-username _repo_username_`*
+
Especifica o nome de usuário necessário para acessar o banco de dados que armazena o repositório.

* *`-port _repo_port_`*
+
Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.

* *`-operation {-operations operation_name [operation_name1, operation_name2] | -all`*
+
Especifica a operação SnapManager para a qual você configura o histórico.

* *`-quiet`*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo de comando

[listing]
----
smsap history purge -profile -name PROFILE1 -operation -operations backup
-verbose
----