---
permalink: windows/reference-the-smosmsapclone-show-command.html 
sidebar: sidebar 
keywords: run, clone, show, command, display, information, database, profile, smsap 
summary: Você pode executar o comando clone show para exibir informações sobre os clones do banco de dados para o perfil especificado. 
---
= O comando smsap clone show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o `clone show` comando para exibir informações sobre os clones do banco de dados para o perfil especificado.



== Sintaxe

[listing]
----

smsap clone show
-profile profile_name
[-id  guid | -label clone_name]
[-quiet | -verbose]
----


== Parâmetros

* *`-profile _profile_name_`*
+
Especifica a lista de clones associados ao perfil. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *`-id _guid_`*
+
Mostra informações sobre o clone com o GUID especificado. O GUID é gerado pelo SnapManager quando você cria um clone. Você pode usar o `smsap clone show` comando para exibir o GUID para cada clone.

* *`-label _label_name_`*
+
Mostra informações sobre o clone com o rótulo especificado.

* *`-quiet`*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *`-verbose`*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

O exemplo a seguir exibe informações sobre o clone:

[listing]
----
smsap clone show -profile SALES1 -label full_backup_sales_May -verbose
----
A saída a seguir mostra informações sobre um clone de um backup no storage primário:

[listing]
----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: E:\ssys1\data_clone\
File: E:\ssys1\data_clone\hsdb\sysaux01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs01.dbf
File: E:\ssys1\data_clone\hsdb\users01.dbf
File: E:\ssys1\data_clone\hsdb\system01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----