---
permalink: windows/task-performing-a-rollback-on-a-single-host-or-multiple-hosts.html 
sidebar: sidebar 
keywords: perform, rollback, single, multiple, snapmanager, server, host, command-line, interface, cli, multiple 
summary: Você pode executar uma reversão em um único ou vários hosts de servidor SnapManager usando a interface de linha de comando. 
---
= Executar uma reversão em um único host ou vários hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar uma reversão em um único ou vários hosts de servidor SnapManager usando a interface de linha de comando (CLI).

Você deve garantir que todos os pré-requisitos para executar uma reversão estejam completos.

. Para executar uma reversão em um único host, digite o seguinte comando:
+
`smsaprepository rollback-repository-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username-portrepo_port-rollbackhosthost_with_target_database`

+
O exemplo a seguir mostra o comando para reverter todos os bancos de dados de destino que são montados no HostA e um banco de dados de repositório chamado repoA localizado no host do repositório, repo_host:

+
[listing]
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA
----
. Para executar uma reversão em vários hosts, digite o seguinte comando: `smsaprepository rollback-repository-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username-portrepo_port-rollbackhosthost_with_target_database1,host_with_target_database2`
+

NOTE: Para vários hosts, insira os nomes de host separados por uma vírgula e certifique-se de que não há espaço entre a vírgula e o próximo nome de host.além disso, certifique-se de inserir todo o conjunto de vários nomes de host dentro de aspas duplas.

+
O exemplo a seguir mostra o comando para reverter todos os bancos de dados de destino que são montados nos hosts, HostA, HostB e um banco de dados de repositório chamado repoA localizado no host do repositório, repo_host:

+
[listing]
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA,hostB
----
+
Os hosts, perfis, programações, backups e clones associados aos perfis dos bancos de dados de destino para o host são revertidos para o repositório anterior.



*Informações relacionadas*

xref:concept-prerequisites-for-performing-a-rollback.adoc[Pré-requisitos para executar uma reversão]
