---
permalink: windows/task-scheduling-backups-with-sap-transaction-db13.html 
sidebar: sidebar 
keywords: enable, backup, snapmanager, sap, dba, plan, calendar, transaction, db13, scheduling, schedule 
summary: Existem várias etapas necessárias para habilitar backups do SnapManager para SAP para funcionar a partir da transação Calendário de Planejamento do DBA DB13. 
---
= Agendar backups com a transação SAP DB13
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem várias etapas necessárias para habilitar backups do SnapManager para SAP para funcionar a partir da transação Calendário de Planejamento do DBA DB13.

. Altere as permissões do diretório /oracle/SID/sapbackup para permitir o acesso de gravação pelo identificador de usuário sidadm.
+
Use o seguinte comando como orasid: `chmod 775 /oracle/SID/sapbackup`

+
Isso permitirá que os membros do dbagroup escrevam para esse diretório. O identificador de usuário sidadm é um membro do grupo dBA.

. Altere as permissões do arquivo de credenciais SnapManager para SAP para orasid para permitir acesso sidadm. Use o seguinte comando executado pelo orasid:
+
Use o seguinte comando executado pelo orasid: `chmod 660 /oracle/SID/.netapp/smsap/credentials`

+
Siga as instruções na seção 3,3, "registrando sistemas no Repositório" do TR-3582 "SnapManager for SAP Best Practices" para Registrar o identificador de usuário sidadm no repositório SnapManager for SAP.


