---
permalink: windows/task-modifying-the-backup-retention-class.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snapmanager, default, backup, retention, class, exist, modify 
summary: Após a atualização, o SnapManager atribui a classe de retenção de backup padrão aos backups existentes. Você pode modificar os valores padrão da classe de retenção para atender aos requisitos de backup. 
---
= Modificação da classe de retenção de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a atualização, o SnapManager atribui a classe de retenção de backup padrão aos backups existentes. Você pode modificar os valores padrão da classe de retenção para atender aos requisitos de backup.

A classe de retenção de backup padrão atribuída aos backups existentes é a seguinte:

|===
| Tipo de cópia de segurança | Atribuição de classe de retenção após a atualização 


 a| 
Backups a serem mantidos para sempre
 a| 
Ilimitado



 a| 
Outros backups
 a| 
Diariamente

|===
*Observação:* você pode excluir os backups que são retidos para sempre sem alterar a classe de retenção.

Se você atualizar para o SnapManager 3,0 ou posterior, o maior dos dois valores a seguir será atribuído aos perfis existentes:

* Contagem de retenção anterior para o perfil
* Valores padrão para a contagem de retenção e duração dos backups diários, conforme especificado no arquivo smsap.config
+
.. Modifique os valores atribuídos a retent.Hourly.count e retent.Hourly.duration no arquivo smsap.config.
+
O arquivo smsap.config está localizado no local de instalação padrão/Properties/smsap.config.

+
Pode introduzir os seguintes valores:

+
*** reter.hourly.count: 12
*** retent.hourly.duração: 2






*Informações relacionadas*

xref:reference-snapmanager-configuration-parameters.adoc[Parâmetros de configuração do SnapManager]
