---
permalink: windows/task-changing-the-retention-policy-default-behavior.html 
sidebar: sidebar 
keywords: backup, expire, retention, policy, snapmanager, delete, setting 
summary: Quando um backup expira com base na política de retenção, o SnapManager determina se deseja excluir o backup com base nas configurações de retenção. A exclusão de backups é o comportamento padrão. Você pode alterar esse comportamento padrão e optar por liberar os backups desprotegidos. 
---
= Alterar o comportamento padrão da política de retenção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um backup expira com base na política de retenção, o SnapManager determina se deseja excluir o backup com base nas configurações de retenção. A exclusão de backups é o comportamento padrão. Você pode alterar esse comportamento padrão e optar por liberar os backups desprotegidos.

Por padrão, o Snap Manager exclui o backup quando eles expiram.

. Acesse o seguinte local padrão:
+
o local de instalação padrão do smsap.config

. Edite o arquivo smsap.config.
. Defina a propriedade ret.alwaysFreeExpiredBackups no arquivo smsap.config como true.
+
Por exemplo, `retain.alwaysFreeExpiredBackups = true`



*Informações relacionadas*

xref:reference-the-smosmsapbackup-update-command.adoc[O comando smsap backup update]
