---
permalink: windows/task-freeing-backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, function, space, smsap 
summary: Você pode liberar backups, o que exclui as cópias Snapshot sem excluir os metadados do backup. Esta função liberta o espaço ocupado pelo backup. Você pode usar o comando smsap backup free para liberar os backups. 
---
= Liberando backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode liberar backups, o que exclui as cópias Snapshot sem excluir os metadados do backup. Esta função liberta o espaço ocupado pelo backup. Você pode usar o comando smsap backup free para liberar os backups.

Para que um backup seja qualificado para liberar, você deve garantir o seguinte:

* A cópia de segurança foi bem-sucedida
* A cópia de segurança não deve ser montada
* O backup não tem clones
* O backup não deve ser retido usando uma política de retenção ilimitada
* A cópia de segurança ainda não foi libertada


Você pode especificar a opção -dump como um parâmetro opcional para coletar os arquivos de despejo após a operação livre de backup bem-sucedida ou com falha.

. Introduza o seguinte comando:
+
`smsap backup free -profile profile_name {-label label [data | -archivelogs] | -id id | -all} -force[-dump] [-quiet] [-force]`



*Informações relacionadas*

xref:reference-the-smosmsapbackup-free-command.adoc[O comando smsap backup free]
