---
permalink: windows/task-previewing-backup-restore-information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, snapmanager, sap, analyze, determine, successful 
summary: Você pode visualizar informações sobre um processo de restauração de backup antes que ele ocorra para ver informações sobre a elegibilidade de restauração que o SnapManager para SAP encontrou no seu backup. O SnapManager analisa os dados do seu backup para determinar se o processo de restauração pode ser concluído com sucesso. 
---
= Pré-visualizar informações de restauro de cópia de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações sobre um processo de restauração de backup antes que ele ocorra para ver informações sobre a elegibilidade de restauração que o SnapManager para SAP encontrou no seu backup. O SnapManager analisa os dados do seu backup para determinar se o processo de restauração pode ser concluído com sucesso.

A visualização de restauração fornece as seguintes informações:

* Que mecanismo de restauração (restauração do sistema de arquivos no lado do storage, restauração de arquivos no lado do storage ou restauração de cópia de arquivo no lado do host) pode ser usado para restaurar cada arquivo.
* Por que mecanismos mais eficientes não foram usados para restaurar cada arquivo, quando você especifica a opção -verbose.


Se você especificar a opção de pré-visualização no comando backup restore, o SnapManager não restaurará nada, mas listará os arquivos a serem restaurados e indicará como eles serão restaurados.


NOTE: Você pode visualizar todos os tipos de mecanismos de restauração. A visualização mostra informações sobre até 20 arquivos.

. Introduza o seguinte comando:``smsap backup restore -profileprofile_name-labellabel-complete -preview -verbose``
+
Por exemplo, digite:

+
[listing]
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
O exemplo a seguir mostra os arquivos prontos para serem restaurados e lista os diferentes métodos usados para cada um:

+
[listing]
----
The following files will be restored via storage side full file system
restore:
E:\disks\sysaux.dbf
E:\disks\system.dbf

The following files will be restored via host side file copy restore:
E:\disks\undotbs1.dbf
E:\disks\undotbs2.dbf
----
. Reveja os motivos pelos quais outros processos de restauração não podem ser usados.
. Inicie a operação de restauração sem a opção -preview, se apenas as razões que são overridable forem exibidas.
+
Você ainda pode substituir verificações não obrigatórias.


