---
permalink: windows/task-reset-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember 
summary: Pode repor a palavra-passe do perfil se não se lembrar da palavra-passe fornecida durante a criação do perfil. 
---
= Repor a palavra-passe do perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode repor a palavra-passe do perfil se não se lembrar da palavra-passe fornecida durante a criação do perfil.



== O que você vai precisar

* Você deve garantir que o servidor SnapManager esteja sendo executado no banco de dados do repositório.
* Você deve ter as credenciais de administrador local do host no qual o banco de dados do repositório está residindo.
* Você deve garantir que o perfil não esteja em uso para nenhuma operação quando a senha estiver sendo redefinida para esse perfil.




== Sobre esta tarefa

Você pode redefinir a senha a partir da CLI ou GUI do SnapManager. Ao redefinir a senha, o SnapManager consulta o servidor SnapManager no host do repositório para identificar o sistema operacional do host do repositório. Você deve inserir as credenciais de usuário autorizado para se conetar ao host do repositório. O servidor SnapManager autentica os usuários com suas credenciais de administrador local no banco de dados do repositório. Quando a autenticação é bem-sucedida, o SnapManager redefine a senha do perfil no servidor SnapManager com a nova senha.


NOTE: O SnapManager não mantém o histórico das operações de redefinição de senha.

.Passo
. Redefina a senha do perfil inserindo o seguinte comando:
+
`*smsap password reset -profile _profile_ [-profile-password _profile_password_] [-repository-hostadmin-password _admin_password_]*`


