---
permalink: windows/task-scheduling-archive-log-file-pruning.html 
sidebar: sidebar 
keywords: create, backup, schedule, pruning, prune, archive, log, file, scheduling 
summary: Quando você cria um backup, você pode agendar a eliminação de arquivos de log de arquivamento para ocorrer em um horário especificado. 
---
= Agendar a eliminação de ficheiros de registo de arquivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você cria um backup, você pode agendar a eliminação de arquivos de log de arquivamento para ocorrer em um horário especificado.

O SnapManager permite que você pode os arquivos de log de arquivamento periodicamente do sistema de arquivos ativo.

. Introduza o seguinte comando:
+
`smsap schedule create -profile profile_name {[-full {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-commentcomment] [-backup-destpath1 [,[path2]] [-exclude-destpath1 [,path2]] [-prunelogs{-all | -untilSCNuntilSCN | -before {-dateyyyy-MM-dd HH:mm:ss | -monthsmonths | -weeksweeks | -daysdays | -hourshours}} -prune-destprune_dest1,prune_dest2] -schedule-nameschedule_name [-schedule-commentschedule_comment] -interval {-hourly | -daily | -weekly | -monthly | -onetimeonly} -cronstringcronstring-start-time {start-timestart_time <yyyy-MM-dd HH:mm>} -runasuser-runasuser [-force] [-quiet | -verbose]`

+
|===
| Se você quiser... | Então... 


 a| 
*Agendar a eliminação de arquivos de log de arquivo*
 a| 
Especifique as seguintes opções:

** -prunelogs para agendar a eliminação dos arquivos de log do arquivo
** -prune-dest para podar arquivos de log do arquivo dos destinos de log do arquivo




 a| 
*Inclua um nome para a programação*
 a| 
Especifique a opção -schedule-name.



 a| 
*Agendar a eliminação de ficheiros de registo de arquivo no intervalo de tempo específico*
 a| 
Especifique a opção de intervalo e indique se os arquivos de log de arquivo devem ser removidos com base nas seguintes classes de intervalo:

** -por hora
** -diariamente
** -semanalmente
** -mensal
** -apenas uma vez




 a| 
*Adicione um comentário sobre a operação de programação*
 a| 
Especifique a opção -schedule-comment seguida da string de descrição.



 a| 
*Especifique a hora de início da operação de programação*
 a| 
Especifique a opção -start-time no formato aaaa-mm-dd hh:mm.

|===

