---
permalink: windows/task-starting-the-snapmanager-graphical-user-interface.html 
sidebar: sidebar 
keywords: snapmanager, install, host, graphical, user, interface, gui, list, program, start 
summary: 'Se o SnapManager estiver instalado no host, inicie a interface gráfica do usuário (GUI) para SnapManager selecionando o programa a partir de uma lista de programas.' 
---
= Iniciando a GUI do SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o SnapManager estiver instalado no host, inicie a interface gráfica do usuário (GUI) do SnapManager selecionando o programa em uma lista de programas.

* Certifique-se de que o servidor SnapManager foi iniciado.


Você pode iniciar a GUI do SnapManager de uma das seguintes maneiras:

* No host do SnapManager, clique em *Iniciar* > *todos os programas* > *NetApp* > *SnapManager para SAP* > *Iniciar GUI do SMSAP*.
* Se o SnapManager não estiver instalado no host, use o Java Web Start, que faz o download dos componentes do SnapManager e inicia a GUI.


*Informações relacionadas*

xref:task-downloading-and-starting-the-graphical-user-interface-using-java-web-start-windows.adoc[Baixando e iniciando a interface gráfica do usuário usando o Java Web Start]
