---
permalink: windows/task-downloading-and-starting-the-graphical-user-interface-using-java-web-start-windows.html 
sidebar: sidebar 
keywords: java, web, start, snapmanager, install, host, download, graphical, user, interface, gui, jre 
summary: 'Você pode usar o Java Web Start se o SnapManager não estiver instalado no host. O Java Web Start faz o download de componentes do SnapManager e inicia a interface gráfica do usuário (GUI). As versões JRE suportadas são 1,5, 1,6 e 1,7.' 
---
= Baixando e iniciando a interface gráfica do usuário usando o Java Web Start
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Java Web Start se o SnapManager não estiver instalado no host. O Java Web Start faz o download de componentes do SnapManager e inicia a interface gráfica do usuário (GUI). As versões JRE suportadas são 1,5, 1,6 e 1,7.

Você deve garantir que as seguintes condições sejam atendidas:

* O servidor SnapManager está em execução.
* Uma janela do navegador da Web está aberta.
+
.. Na janela do navegador da Web do Microsoft Internet Explorer, digite https://smsap-server.domain.com:port[].
+
smsap-server.domain.com é o nome de host e domínio totalmente qualificados no qual você instalou o SnapManager e a porta é a porta de escuta para o servidor SnapManager (27314, por padrão).

+

NOTE: Você deve inserir https na janela do navegador.

+
É apresentada uma caixa de diálogo com a mensagem existe um problema com o certificado de segurança do site... pretende continuar?.

.. Clique em *Sim* ou *continuar*.
.. Clique no link rotulado clique aqui para baixar e instalar o JRE 6,0 e o aplicativo.
+
Um link rotulado Baixar Java Web Iniciar com a mensagem este site pode exigir o seguinte controle ActiveX: Java Plug-in 1,6"... "Clique aqui para instalar é exibido.

.. Na janela Instalar, execute as seguintes etapas:
+
... Clique na mensagem rotulada clique aqui para instalar....
+
É apresentado um menu *Instalar controlo ActiveX*.

... Selecione *Instalar controlo ActiveX...*.
+
A mensagem Internet Explorer - Aviso de segurança" contendo o seguinte texto: "Deseja instalar este software? Nome: Java Plug-in 1,6 é exibido.

... Clique em *Instalar*.
+
Uma janela "Java Plug-in 1,6." para o instalador do J2SE Runtime Environment 1,6 é exibida.

... Clique em *Instalar*.


+
Uma janela solicitando a instalação do J2SE Runtime Environment 1,6 é exibida.

.. Na janela Instalar, execute as seguintes etapas:
+
... Na página Contrato de Licença, selecione *Aceito os termos do contrato de licença* e clique em *Avançar*.
... Na página tipo de configuração, selecione *típica* e clique em *seguinte*.
... Na janela Instalação concluída, clique em *Finish*.
+
O SnapManager começa a baixar.



+
Uma caixa de diálogo Download de arquivo com a mensagem deseja salvar esse arquivo? Application.jnlp é exibida.

.. Na janela de download do arquivo, execute as seguintes etapas:
+
... Instale a versão mais recente do JRE 1,6 no cliente Windows.
... Verifique se o Java está instalado executando o seguinte comando: `java -version`
+
A saída deve indicar Java versão 1,6.0_24 (que é Java 1,6) ou posterior.

... Altere as configurações do Windows para sempre abrir arquivos com extensão jnlp com o programa Java Web Start Launcher.
+
As etapas para alterar as configurações do Windows variam de acordo com a versão do Windows que você está usando.

... Digite o URL do SnapManager que você especificou na etapa 1.




+
O download do SnapManager é iniciado no cliente Windows e uma caixa de diálogo Aviso - segurança é exibida.

+
.. Execute as etapas a seguir.
+
O conteúdo da mensagem e os rótulos dos botões variam de acordo com a plataforma.

+
... Na caixa de diálogo Aviso - Segurança, clique em *Sim*.
+
É apresentada uma caixa de diálogo.

... Na caixa de diálogo incompatibilidade do nome do host, clique em *Executar*.
+
A caixa de diálogo Aviso - Segurança com uma mensagem sobre a assinatura do aplicativo SnapManager é exibida.

... Clique em *Executar*.
+
Uma caixa de diálogo com o título Instalador Java - Aviso de Segurança e a mensagem Segurança de Aviso - a assinatura digital do aplicativo tem um erro. Pretende executar a aplicação, é apresentado.

... Clique em *Executar*.
+
O navegador faz o download e inicia a GUI do SnapManager para SAP.






