---
permalink: windows/task-creating-backup-schedules.html 
sidebar: sidebar 
keywords: schedule, backup, time, frequency, suit, data, environment, creating, create 
summary: Você pode agendar um backup para ocorrer no momento e na frequência adequados para seus dados e ambiente. 
---
= Criação de agendas de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode agendar um backup para ocorrer no momento e na frequência adequados para seus dados e ambiente.

No SnapManager 3,2 para SAP, você pode agendar os backups dos arquivos de log de arquivamento separadamente. No entanto, você deve usar o perfil que você criou para separar os arquivos de log do arquivo.

Se você tiver agendado os backups dos arquivos de dados e arquivos de log de arquivamento ao mesmo tempo, o SnapManager cria primeiro o backup dos arquivos de dados.

Se você selecionar o intervalo de programação como -onetimeonly, todas as opções de poda estarão disponíveis. Se você selecionar um intervalo de programação diferente de -onetimeonly, as opções de eliminação -until-SCN e -until-date não serão suportadas e a seguinte mensagem de erro será exibida: A opção de eliminação de log de arquivo especificada, -until-scn ou -until-date para o intervalo de programação por hora é inválida. Especifique a opção -onetimeonly para o intervalo de programação ou pode os logs de arquivo usando qualquer uma das opções All, ou -before

Quando um failover acontece em ambientes de cluster de failover de servidor Microsoft Windows (WSFC) e servidor de cluster Microsoft (MSCS), você deve reiniciar o servidor SnapManager para SAP para que o endereço de serviço (virtual) seja mapeado para o host ativo e as programações do SnapManager sejam ajustadas para o host SnapManager ativo.


NOTE: Se o mesmo nome de perfil e programação existir em outro repositório, a operação de agendamento de backup não será iniciada nesse repositório. A operação será encerrada com a seguinte mensagem: A operação já está em execução.

. Introduza o seguinte comando: `smsap schedule create -profile profile_name {[-full {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-commentcomment][-backup-destpath1 [,[path2]] [-exclude-destpath1 [,path2]] [-prunelogs{-all | -untilSCNuntilSCN | -until-dateyyyy-MM-dd HH:mm:ss | -before {-months | -weeks | -days | -hours}} -prune-destprune_dest1,prune_dest2] -schedule-nameschedule_name [-schedule-commentschedule_comment] -interval {-hourly | -daily | -weekly | -monthly | -onetimeonly} -cronstringcronstring-start-time {start-timestart_time <yyyy-MM-dd HH:mm\>} -runasuser-runasuser [-force] [-taskspec-taskspec] [-quiet | -verbose]`
+
|===
| Se você quiser... | Então... 


 a| 
*Agendar um backup de um banco de dados on-line ou off-line*
 a| 
Especifique -off-line ou -online para agendar um backup do banco de dados off-line ou on-line. Se você especificar essas opções, não poderá usar -auto.



 a| 
*Deixe o SnapManager lidar com o agendamento de um banco de dados, independentemente de ele estar on-line ou off-line*
 a| 
Especifique -auto. Se você especificar -auto, você não pode usar --off-line ou -online.



 a| 
*Agendar um backup de arquivos de dados*
 a| 
Especifique -data -files para listar os arquivos separados por vírgulas. Por exemplo, use nomes de arquivo F1,F2,F3.



 a| 
*Agendar um backup parcial de espaços de tabela específicos*
 a| 
Especifique -tablespaces para listar as tablespaces separadas por vírgulas. Por exemplo, use TS1,TS2,TS3.



 a| 
*Agendar backup de arquivos de log de arquivo*
 a| 
Especifique o seguinte:

** -archivelogs para agendar backup dos arquivos de log do arquivo
** -backup-dest para agendar destinos de arquivo de log a serem incluídos no backup
** -excluir-dest para agendar os destinos de log de arquivo a serem excluídos do backup




 a| 
*Especifique os valores da classe de retenção*
 a| 
Especifique -retent e indique se o backup deve ser mantido de acordo com uma das seguintes classes de retenção:

** -por hora
** -diariamente
** -semanalmente
** -mensal
** -Ilimitado SnapManager padrão para hora.




 a| 
*Agendar a eliminação de arquivos de log de arquivo*
 a| 
Especifique o seguinte: ** -Prunelogs para podar os arquivos de log do arquivo enquanto estiver programando um backup ** -Prune-dest para especificar o destino do log do arquivo a partir do qual os arquivos de log do arquivo são podados



 a| 
*Inclua um nome para a programação*
 a| 
Especifique -schedule-name.



 a| 
*Programe o backup do banco de dados em um intervalo de tempo específico*
 a| 
Especifique a opção de intervalo e selecione o intervalo de tempo a partir do seguinte, pelo qual os backups devem ser criados:

** -por hora
** -diariamente
** -semanalmente
** -mensal
** -apenas uma vez




 a| 
*Configurar uma programação*
 a| 
Especifique -cronstring e inclua as sete subexpressões a seguir que descrevem a opção individual:

** 1 refere-se a segundos.
** 2 refere-se a minutos.
** 3 refere-se a horas.
** 4 refere-se a um dia em um mês.
** 5 refere-se ao mês.
** 6 refere-se a um dia em uma semana.
** (Opcional) 7 refere-se ao ano. *Nota:* se você programou seu backup com diferentes momentos em -cronstring e -start-time, então a programação do backup é sobrescrita e acionada pelo -start-time.




 a| 
*Adicione um comentário sobre o agendamento de backup*
 a| 
Especifique -schedule-comment seguido da string de descrição.



 a| 
*Especifique a hora de início da operação de programação*
 a| 
Especifique -start-time no formato aaaa-mm-dd hh:mm.



 a| 
*Altere o usuário da operação de backup agendada ao agendar o backup*
 a| 
Especifique -runasuser. A operação é executada como o usuário (usuário raiz ou usuário Oracle) que criou a programação. No entanto, você pode usar seu próprio ID de usuário, se você tiver credenciais válidas para o perfil do banco de dados e o host.



 a| 
*Ative uma atividade de pré-tarefa ou pós-tarefa da operação de agendamento de backup usando o arquivo XML de especificação de pré-tarefa e pós-tarefa*
 a| 
Especifique a opção -taskspec e forneça o caminho absoluto do arquivo XML de especificação de tarefa para executar uma atividade de pré-processamento ou pós-processamento para ocorrer antes ou depois da operação de agendamento de backup.

|===

