---
permalink: windows/task-updating-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, updating, associate 
summary: 'O SnapManager (3,2 ou posterior) para SAP fornece a capacidade de atualizar o nome do host do banco de dados de destino no perfil do SnapManager.' 
---
= Atualizando o nome do host do banco de dados de destino associado a um perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager (3,2 ou posterior) para SAP oferece a capacidade de atualizar o nome do host do banco de dados de destino no perfil do SnapManager.

* O diretório home do usuário local deve estar ciente dos mapeamentos de perfil para repositório.
* As sessões da interface gráfica do usuário (GUI) do SnapManager devem ser fechadas.


Você pode atualizar o perfil com o novo nome de host usando apenas a CLI.

*Cenários não suportados para alterar o nome do host do banco de dados de destino no perfil*

Os cenários a seguir não são suportados para alterar o nome do host do banco de dados de destino no perfil:

* Alterar o nome do host do banco de dados de destino usando a GUI do SnapManager
* Reverter o banco de dados do repositório depois de atualizar o nome do host do banco de dados de destino do perfil
* Atualizando vários perfis para um novo nome de host de banco de dados de destino executando um único comando
* Alterar o nome do host do banco de dados de destino quando qualquer operação do SnapManager estiver em execução



NOTE: Depois de atualizar o nome do host do banco de dados de destino no perfil, somente o nome do host do banco de dados de destino será alterado. Todos os outros parâmetros de configuração definidos no perfil são retidos.

Depois de atualizar o nome do host do banco de dados de destino, você não poderá excluir ou desmontar o backup se o clone ou o backup montado não estiver disponível no novo host. Em tais cenários, executar as operações do SnapManager do novo host leva à falha, bem como entradas obsoletas no host anterior. Para executar operações do SnapManager, você deve reverter para o nome de host anterior usando a atualização de perfil.

.Passos
. Introduza o seguinte comando:
+
`smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port]] [{-rman{-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`

+
Outras opções para este comando são as seguintes:

+
[-force] [-noprompt]

+
|===
| Se você quiser... | Então... 


 a| 
*Altere o nome do host do banco de dados de destino*
 a| 
Especifique -hostnew_dB_host

|===
. Para exibir o nome do host do banco de dados de destino do perfil, digite o seguinte comando:
+
`smsap profile show`


