---
permalink: windows/task-mounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, host, available, scenario, tools, oracle, recovery, manager, rman, file 
summary: 'O SnapManager manipula automaticamente a montagem de um backup para disponibilizá-lo ao host. Você também pode montar backups em cenários em que você usa uma ferramenta externa, como o Oracle Recovery Manager (RMAN), para acessar os arquivos no backup.' 
---
= Montagem de backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager manipula automaticamente a montagem de um backup para disponibilizá-lo ao host. Você também pode montar backups em cenários em que você usa uma ferramenta externa, como o Oracle Recovery Manager (RMAN), para acessar os arquivos no backup.

O comando smsap backup mount exibe uma lista de caminhos onde as cópias Snapshot que consistem no backup foram montadas.


NOTE: Opcionalmente, você pode coletar os arquivos de despejo após uma operação de montagem de backup bem-sucedida ou com falha.

. Para montar uma cópia de segurança, introduza o seguinte comando:
+
`smsap backup mount -profile profile_name label [data | -archivelogs] | -id id} [-host-host] [-dump] [-quiet | -verbose]`



*Informações relacionadas*

xref:reference-the-smosmsapbackup-mount-command.adoc[O comando smsap backup mount]
