---
permalink: windows/task-configure-e-mail-notification-for-a-new-profile.html 
sidebar: sidebar 
keywords: create, profile, configure, receive, email, notification, completion, database, operation, profile 
summary: Ao criar um novo perfil, você pode configurar para receber uma notificação por e-mail após a conclusão da operação do banco de dados. 
---
= Configurar notificação por e-mail para um novo perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar um novo perfil, você pode configurar para receber uma notificação por e-mail após a conclusão da operação do banco de dados.



== O que você vai precisar

* Você deve configurar o endereço de e-mail a partir do qual os alertas são enviados.
* Você deve usar uma lista separada por vírgulas para vários endereços de e-mail.
+
Você deve garantir que não há espaço entre a vírgula e o próximo endereço de e-mail.

+

NOTE: Você deve garantir que você insira o conjunto de endereços de e-mail dentro de aspas duplas.



.Passo
. Introduza o seguinte comando:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [ ]][-notification [-success-email _email_address1_,_email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_,_email_address2_ -subject _subject_pattern_]]*`

+
Outras opções para este comando são as seguintes:

+
[`-force`]

+
[`quiet` `-verbose` | ]

+

NOTE: O SnapManager suporta até 1000 carateres para endereços de e-mail.

+
Quando você cria um backup de arquivos de dados e arquivos de log de arquivamento juntos usando o perfil (para criar backups de log de arquivamento separados) e a criação de backup de arquivo de dados falha, a notificação de e-mail é enviada com o backup de dados como o nome da operação em vez de backup de dados e backup de logs de arquivamento. Quando a operação de cópia de segurança do ficheiro de registo de dados e do ficheiro de registo de arquivo for bem-sucedida, verá a saída da seguinte forma:

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----

