---
permalink: windows/task-setting-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, set 
summary: Depois de limpar o cache para remover as credenciais de usuário armazenadas, você pode definir as credenciais para os hosts, repositórios e perfis. 
---
= Configurando credenciais após limpar o cache de credenciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de limpar o cache para remover as credenciais de usuário armazenadas, você pode definir as credenciais para os hosts, repositórios e perfis.

Você deve garantir que você defina as mesmas credenciais de usuário para o repositório, host de perfil e perfil que você forneceu anteriormente. Um arquivo de credenciais criptografadas é criado ao definir as credenciais do usuário.

O arquivo de credenciais está localizado em C: Documentos e Configurações, dados do administrador/aplicativo, NetApp/smsap/3,3.0.

Na interface gráfica do usuário (GUI) do SnapManager, se não houver repositório em repositórios, execute as seguintes etapas:

. Clique em *tarefas* > *Adicionar Repositório existente* para adicionar um repositório existente.
. Execute as seguintes etapas para definir as credenciais para o repositório:
+
.. Clique com o botão direito do rato no repositório e selecione *Open*.
.. Na janela Autenticação de credenciais do Repositório, insira as credenciais do usuário.


. Execute as seguintes etapas para definir as credenciais para o host:
+
.. Clique com o botão direito do Mouse no host sob o repositório e selecione *Open*.
.. Na janela Autenticação de credenciais do host, insira as credenciais do usuário.


. Execute as seguintes etapas para definir as credenciais para o perfil:
+
.. Clique com o botão direito do Mouse no perfil sob o host e selecione *Open*.
.. Na janela Autenticação de credenciais de perfil, insira as credenciais do usuário.



