---
permalink: windows/task-adding-existing-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, add, exist, profile, summary, email, notification, updating, update 
summary: O SnapManager permite adicionar um perfil existente a uma notificação de e-mail de resumo durante a atualização desse perfil. 
---
= Adicionando um perfil existente às notificações de resumo por e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager permite adicionar um perfil existente a uma notificação de e-mail de resumo durante a atualização desse perfil.

. Introduza o seguinte comando: `smsap profile update -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | \{-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly-countn] [-durationm]] [-daily-countn] [-durationm]] [-weekly-countn] [-durationm]] [-monthly-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-summary-notification]`

