---
permalink: unix-administration/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, operation, manage, managing, efficient 
summary: Você deve criar um perfil no SnapManager para o banco de dados no qual deseja executar uma operação. Tem de selecionar o perfil e, em seguida, selecionar a operação que pretende executar. 
---
= Gerenciamento de perfis para backups eficientes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar um perfil no SnapManager para o banco de dados no qual deseja executar uma operação. Tem de selecionar o perfil e, em seguida, selecionar a operação que pretende executar.



== Tarefas relacionadas a perfis

Você pode executar as seguintes tarefas:

* Crie perfis para habilitar backups e backups completos ou parciais para storage primário, secundário ou até terciário.
+
Você também pode criar perfis para separar os backups de log de arquivamento dos backups de arquivos de dados.

* Verifique os perfis.
* Atualizar perfis.
* Eliminar perfis.




== Sobre perfis e autenticação

Ao criar um perfil, você pode especificar um banco de dados e escolher um dos seguintes métodos para se conetar ao banco de dados:

* Autenticação Oracle com um nome de usuário, senha e porta
* Autenticação do sistema operacional (SO) sem nome de usuário, senha ou porta.
+
Para autenticação do SO, tem de introduzir as informações do utilizador e do grupo da conta do SO.

+

NOTE: Para usar a autenticação do sistema operacional para os bancos de dados RAC (Real Application Cluster), o servidor SnapManager deve estar em execução em cada nó do ambiente RAC e a senha do banco de dados deve ser a mesma para todas as instâncias Oracle em um ambiente RAC. O SnapManager usa o nome de usuário e a senha do banco de dados para se conetar a todas as instâncias do RAC no perfil.

* Autenticação de banco de dados `sqlnet.authentication_services` quando está definido como `*NONE*`. Em seguida, o SnapManager usa o nome de usuário e a senha do banco de dados para todas as conexões com o banco de dados de destino.
+

NOTE: Para usar a autenticação do banco de dados para uma instância do Gerenciamento Automático de armazenamento (ASM), você deve inserir o nome de usuário e a senha que você usa para fazer login na instância do ASM.



Você pode definir `sqlnet.authentication_services` como `*NONE*` somente nos seguintes ambientes:

[cols="1a,1a,1a,1a"]
|===
| Layout do banco de dados | Versão Oracle | A autenticação de banco de dados é suportada para o banco de dados de destino | A autenticação de banco de dados é suportada para a instância ASM 


 a| 
Qualquer banco de dados não ASM e não RAC
 a| 
Oracle 10gi e Oracle 11gi (menor que 11,2.0,3)
 a| 
Sim
 a| 
Não



 a| 
Banco de dados ASM autônomo no UNIX
 a| 
Oracle 11.2.0.3 e posterior
 a| 
Sim
 a| 
Sim



 a| 
Instância ASM no banco de dados RAC no UNIX
 a| 
Oracle 11.2.0.3g.
 a| 
Não
 a| 
Não



 a| 
Banco de dados RAC no NFS
 a| 
Oracle 11.2.0.3g.
 a| 
Sim
 a| 
Não

|===

NOTE: Depois de desativar `sqlnet.authentication_services` e alterar o método de autenticação para autenticação de banco de dados, você deve definir `sqlnet.authentication_services` como `*NONE*`.

Se estiver a aceder a um perfil pela primeira vez, tem de introduzir a palavra-passe do perfil. Depois de inserir suas credenciais, você pode exibir os backups do banco de dados dentro do perfil.
