---
permalink: unix-administration/concept-prerequisites-for-data-protection.html 
sidebar: sidebar 
keywords: aware, certain, consideration, perform, data, protection 
summary: Você precisa estar ciente de algumas considerações para executar a proteção de dados. 
---
= Considerações para executar a proteção de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa estar ciente de algumas considerações para executar a proteção de dados.

* Para executar operações de clone ou restauração de sistemas secundários, é necessário montar o volume de destino no namespace e exportá-lo corretamente.
* É necessário desativar o parâmetro de configuração do SnapDrive `check-export-permission-nfs-clone` definindo o valor como `*off*`.
+
A documentação do SnapDrive para UNIX no site de suporte da NetApp contém informações adicionais sobre o `check-export-permission-nfs-clone` parâmetro.

* É necessário configurar a relação do SnapMirror para os volumes de storage secundário solicitados no sistema de storage secundário.
* Você deve configurar a relação SnapVault para os qtrees de armazenamento secundário solicitados no sistema de armazenamento secundário para Data ONTAP operando no modo 7.
* Você deve definir uma política e regras para o rótulo SnapMirror definido pelo usuário se estiver usando o pós-script do SnapVault para o Clustered Data ONTAP.
+
O pós-script do SnapVault é compatível com volumes Data ONTAP em cluster e com os tipos de relação SnapMirror DP e XDP. A documentação do ONTAP no site de suporte da NetApp contém informações sobre a configuração do SnapMirror e do SnapVault.

* Em ambientes nas, você deve configurar o caminho de dados nas primário e secundário usando o `snapdrive config set -mgmtpath _management_path management_path management_path datapath_path_` comando.
+
Por exemplo, `*snapdrive config set -mgmtpath f3050-197-91 f3050-197-91 f3050-197-91 f3050-220-91*`, `f3050-197-91` onde está o caminho de gerenciamento e `f3050-220-91` é o caminho de dados.



http://mysupport.netapp.com/["Documentação no site de suporte da NetApp"^]
