---
permalink: unix-administration/concept-details-of-the-target-database.html 
sidebar: sidebar 
keywords: example, integrate, database, protection, payroll, example, detail, target 
summary: Este exemplo de proteção de banco de dados integrada descreve a proteção de um banco de dados de folha de pagamento. Os seguintes dados são usados no exemplo. 
---
= Detalhes do banco de dados de destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este exemplo de proteção de banco de dados integrada descreve a proteção de um banco de dados de folha de pagamento. Os seguintes dados são usados no exemplo.

O administrador de banco de dados (DBA) da TechCo, uma empresa de 3000 pessoas com sede em Atlanta, deve criar um backup consistente do banco de dados de folha de pagamento de produção, PAYDB. A estratégia de proteção para backup em storage primário e secundário requer que o DBA e o administrador de storage trabalhem juntos para fazer backup do banco de dados Oracle localmente no storage primário e também remotamente, para o armazenamento secundário em um local remoto.

* *Informações de perfil*
+
Ao criar um perfil no SnapManager, você precisa dos seguintes dados:

+
** Nome do banco de dados: P01
** Nome do anfitrião: prod01.sample.com
** ID da base de dados: P01
** Nome do perfil: P01_BACKUP
** Modo de conexão: Autenticação de banco de dados
** Esquema de nomeação de instantâneos: `_smsap_hostname_dbsid_smsapprofile_scope_mode_smid_` (Que se traduz em "smsap_prod01.sample.com_p01_p01_backup_f_h_x")
** Usuário do repositório: <sid> representante, que se traduz em p01rep.



