---
permalink: unix-administration/concept-limitations.html 
sidebar: sidebar 
keywords: scenario, limitation, environment, snapmanager 
summary: Você deve estar ciente dos cenários e limitações que podem afetar seu ambiente. 
---
= Limitações ao trabalhar com o SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente dos cenários e limitações que podem afetar seu ambiente.

*Limitações relacionadas a layouts e plataformas de banco de dados*

* O SnapManager suporta arquivos de controle em um sistema de arquivos e não suporta arquivos de controle em dispositivos brutos.
* O SnapManager opera em um ambiente de cluster da Microsoft (MSCS), mas não reconhece o estado da configuração MSCS (ativa ou passiva) e não transfere o gerenciamento ativo de um repositório para um servidor de reserva em um cluster MSCS.
* No Red Hat Enterprise Linux (RHEL) e Oracle Enterprise Linux 4,7, 5,0, 5,1, 5,2 e 5,3, o sistema de arquivos ext3 não é suportado ao implantar o Oracle em dispositivos brutos usando o Dynamic Multipathing (DMP) em um ambiente de e/S de rede multipath (MPIO).
+
Esse problema é notado no SnapManager somente quando se usa o SnapDrive 4,1 para UNIX ou versões anteriores.

* O SnapManager no RHEL não suporta particionamento de discos usando o utilitário *parted*.
+
Este é um problema com o utilitário RHEL *parted*.

* Em uma configuração RAC, quando um nome de perfil é atualizado a partir do nó RAC A, o arquivo de agendamento para o perfil é atualizado apenas para o nó RAC A.
+
O arquivo de agendamento para o mesmo perfil no nó RAC B não é atualizado e contém as informações de agendamento anteriores. Quando um backup agendado é acionado a partir do nó B, a operação de backup agendada falha porque o nó B contém o arquivo de agendamento anterior. No entanto, a operação de backup agendada é bem-sucedida do nó A, no qual o perfil é renomeado. Você pode reiniciar o servidor SnapManager para que você receba o arquivo de agendamento mais recente para o perfil no nó B.

* O banco de dados do repositório pode existir em um host que pode ser acessado usando mais de um endereço IP.
+
Se o repositório for acessado usando mais de um endereço IP, o arquivo de agendamento será criado para cada um dos endereços IP. Se o backup de agendamento for criado para um perfil (por exemplo, perfil A) em um dos endereços IP (por exemplo, IP1), o arquivo de agendamento somente para esse endereço IP será atualizado. Se o perfil A for acessado de outro endereço IP (por exemplo, IP2), o backup agendado não será listado porque o arquivo de agendamento do IP2 não tem uma entrada para o agendamento criado em IP1.

+
Você pode esperar que a programação seja acionada a partir desse endereço IP e do arquivo de agendamento a ser atualizado, ou você pode reiniciar o servidor.



*Limitações relacionadas à configuração do SnapManager*

* O SnapDrive para UNIX suporta mais de um tipo de sistema de arquivos e gerenciador de volume em determinadas plataformas.
+
O sistema de arquivos e o gerenciador de volumes usados para arquivos de banco de dados devem ser especificados no arquivo de configuração do SnapDrive como sistema de arquivos padrão e gerenciador de volumes.

* O SnapManager dá suporte a bancos de dados em sistemas de storage MultiStore com os seguintes requisitos:
+
** Você deve configurar o SnapDrive para definir senhas para sistemas de armazenamento MultiStore.
** O SnapDrive não pode criar uma cópia Snapshot de um LUN ou arquivo residente em uma qtree em um sistema de storage MultiStore se o volume subjacente não estiver no mesmo sistema de storage MultiStore.


* O SnapManager não suporta o acesso a dois servidores SnapManager executados em portas diferentes de um único cliente (tanto da CLI quanto da GUI).
+
Os números das portas devem ser os mesmos nos hosts de destino e remotos.

* Todos os LUNs dentro de um volume devem residir no nível de volume ou dentro do qtrees, mas não ambos.
+
Isso ocorre porque se os dados estão residindo no qtrees e você monta o volume, então os dados dentro do qtrees não são protegidos.

* As operações do SnapManager falham e você não pode acessar a GUI quando o banco de dados do repositório está inativo.
+
Você deve verificar se o banco de dados do repositório está sendo executado quando você executa quaisquer operações do SnapManager.

* O SnapManager não suporta mobilidade de partição ao vivo (LPM) e mobilidade de aplicativos ao vivo (LAM).
* O SnapManager não oferece suporte ao Oracle Wallet Manager e à criptografia de dados transparente (TDE).
* O SnapManager não oferece suporte a configurações MetroCluster em ambientes de mapeamento de dispositivos brutos (RDM) porque as configurações do MetroCluster ainda não têm suporte para o console de storage virtual (VSC).


*Limitações relacionadas à gestão de perfis*

* Se você atualizar o perfil para separar os backups do log de arquivamento, não será possível executar uma operação de reversão no host.
* Se você habilitar um perfil da GUI para criar backups de log de arquivamento e, mais tarde, tentar atualizar o perfil usando a janela Atualização de vários perfis ou a janela Atualização de perfil, não será possível modificar esse perfil para criar um backup completo.
* Se você atualizar vários perfis na janela Atualização de vários perfis e alguns perfis tiverem a opção *Backup Archivelogs separately* ativada e outros perfis tiverem a opção desativada, a opção *Backup Archivelogs separately* será desativada.
* Se você atualizar vários perfis e alguns perfis tiverem a opção *Backup Archivelogs separately* ativada e outros perfis tiverem a opção desativada, a opção *Backup Archivelogs separately* na janela Atualização de vários perfis será desativada.
* Se você renomear o perfil, não poderá reverter o host.


*Limitações relacionadas a operações de atualização contínua ou reversão*

* Se você tentar instalar uma versão anterior do SnapManager para um host sem executar a operação de reversão no host no repositório, talvez não seja possível fazer o seguinte:
+
** Visualize os perfis criados em versões anteriores ou posteriores do SnapManager para o host.
** Acesse backups ou clones criados em versões anteriores ou posteriores do SnapManager.
** Execute operações de atualização contínua ou reversão no host.


* Depois de separar os perfis para criar backups de log de arquivamento, não é possível executar uma operação de reversão no repositório de host relacionado.


*Limitações relacionadas às operações de backup*

* Durante a recuperação, se o backup já estiver montado, o SnapManager não montará o backup novamente e usará o backup já montado.
+
Se o backup for montado por um usuário diferente e você não tiver acesso ao backup montado anteriormente, o outro usuário deve fornecer a permissão.

+
Todos os arquivos de log de arquivamento têm permissão de leitura para usuários atribuídos a um grupo; talvez você não tenha permissão de acesso ao arquivo de log de arquivamento, se o backup for montado por um grupo de usuários diferente. Os usuários podem dar permissão aos arquivos de log de arquivo montados manualmente e, em seguida, tentar novamente a operação de restauração ou recuperação.

* O SnapManager define o estado do backup como "PROTEGIDO", mesmo quando uma das cópias Snapshot do backup do banco de dados é transferida para o sistema de storage secundário.
* Você pode usar o arquivo de especificação de tarefa para backup agendado somente a partir do SnapManager 3,2 ou posterior.
* O SnapManager integrado ao Gerenciador de proteção dá suporte ao backup de vários volumes no storage primário para um único volume no storage secundário para SnapVault e qtree SnapMirror.
+
O dimensionamento dinâmico de volumes secundários não é suportado. O Provisioning Manager and Protection Manager Administration Guide for Use with DataFabric Manager Server 3,8 tem para obter mais informações sobre isso.

* O SnapManager não suporta o uso de cofres de backups usando o script de pós-processamento.
* Se o banco de dados do repositório estiver apontando para mais de um endereço IP e cada endereço IP tiver um nome de host diferente, a operação de agendamento de backup será bem-sucedida para um endereço IP, mas falhará para o outro endereço IP.
* Após a atualização para o SnapManager 3,4 ou posterior, não é possível atualizar os backups programados com scripts de pós-processamento usando o SnapManager 3.3.1.
+
Tem de eliminar a agenda existente e criar uma nova agenda.



*Limitações relacionadas às operações de restauração*

* Quando você usa um método indireto para executar uma operação de restauração e os arquivos de log de arquivamento necessários para recuperação estão disponíveis apenas em backups do sistema de storage secundário, o SnapManager falha em recuperar o banco de dados.
+
Isso ocorre porque o SnapManager não pode montar o backup de arquivos de log de arquivamento a partir do sistema de armazenamento secundário.

* Quando o SnapManager executa uma operação de restauração de volume, as cópias de backup de log de arquivamento feitas após a restauração do backup correspondente não são purgadas.
+
Quando os ficheiros de dados e o destino do ficheiro de registo de arquivo existirem no mesmo volume, os ficheiros de dados podem ser restaurados através de uma operação de restauro de volume se não existirem ficheiros de registo de arquivo disponíveis no destino do ficheiro de registo de arquivo. Nesse cenário, as cópias Snapshot do log de arquivamento que são criadas após o backup dos arquivos de dados são perdidas.

+
Não deve eliminar todos os ficheiros de registo de arquivo do destino do registo de arquivo.



*Limitações relacionadas às operações de clone*

* Não é possível visualizar quaisquer valores numéricos entre 0 e 100 para o progresso da operação de divisão de clones devido à velocidade com que os inodes são descobertos e processados pelo sistema de armazenamento que contém o volume flexível.
* O SnapManager não dá suporte ao recebimento de e-mails apenas para as operações de divisão de clones bem-sucedidas.
* O SnapManager suporta apenas a divisão de um FlexClone.
* A clonagem do backup do banco de dados on-line do banco de dados RAC que usa o local do arquivo de log de arquivamento externo falha devido a falha na recuperação.
+
A clonagem falha porque o Oracle não consegue localizar e aplicar os arquivos de log de arquivamento para recuperação a partir do local de log de arquivamento externo. Esta é uma limitação Oracle. Para obter mais informações, consulte o ID de Bug do Oracle: 13528007. O Oracle não aplica o log de arquivamento do local não padrão no http://metalink.oracle.com/["Site de suporte Oracle"^]. Você deve ter um nome de usuário e senha válidos do Oracle metalink.

* O SnapManager 3,3 ou posterior não suporta o uso do arquivo XML de especificação clone criado nas versões anteriores ao SnapManager 3,2.
* Se as tablespaces temporárias estiverem localizadas em um local diferente do local de datafiles, uma operação clone criará as tablespaces no local de datafiles.
+
No entanto, se as tabelas temporárias forem os arquivos gerenciados Oracle (OMFs) que estão localizados em um local diferente do local de arquivos de dados, a operação clone não criará os espaços de tabela no local de arquivos de dados. Os OMFs não são gerenciados pelo SnapManager.

* O SnapManager não consegue clonar um banco de dados RAC se você selecionar `-resetlogs` a opção.


*Limitações relacionadas a arquivos de log de arquivo e backups*

* O SnapManager não suporta a eliminação de ficheiros de registo de arquivo a partir do destino da área de recuperação flash.
* O SnapManager não suporta a eliminação de ficheiros de registo de arquivo a partir do destino de espera.
* Os backups de log de arquivamento são mantidos com base na duração de retenção e na classe de retenção padrão por hora.
+
Quando a classe de retenção de backup de log de arquivamento é modificada usando a CLI ou GUI do SnapManager, a classe de retenção modificada não é considerada para backup porque os backups de log de arquivamento são mantidos com base na duração da retenção.

* Se eliminar os ficheiros de registo de arquivo dos destinos de registo de arquivo, a cópia de segurança de registo de arquivo não inclui ficheiros de registo de arquivo mais antigos do que o ficheiro de registo de arquivo em falta.
+
Se o arquivo de log de arquivamento mais recente estiver ausente, a operação de backup de log de arquivamento falhará.

* Se eliminar os ficheiros de registo de arquivo dos destinos de registo de arquivo, a eliminação dos ficheiros de registo de arquivo falhará.
* O SnapManager consolida os backups do log de arquivamento, mesmo quando você exclui os arquivos de log de arquivamento dos destinos do log de arquivamento ou quando os arquivos de log de arquivamento estão corrompidos.


*Limitações relacionadas à alteração do nome do host do banco de dados de destino*

As seguintes operações do SnapManager não são suportadas quando você altera o nome do host do banco de dados de destino:

* Alterando o nome do host do banco de dados de destino da GUI do SnapManager.
* Reverter o banco de dados do repositório depois de atualizar o nome do host do banco de dados de destino do perfil.
* Atualizar simultaneamente vários perfis para um novo nome de host de banco de dados de destino.
* Alterar o nome do host do banco de dados de destino quando qualquer operação do SnapManager estiver em execução.


*Limitações relacionadas ao CLI ou GUI do SnapManager*

* Os comandos CLI do SnapManager para `profile create` a operação que são gerados a partir da GUI do SnapManager não têm opções de configuração de histórico.
+
Você não pode usar o `profile create` comando para configurar as configurações de retenção de histórico a partir da CLI do SnapManager.

* O SnapManager não exibe a GUI no Mozilla Firefox quando não há ambiente de tempo de execução Java (JRE) disponível no cliente UNIX.
* Ao atualizar o nome do host do banco de dados de destino usando a CLI do SnapManager, se houver uma ou mais sessões de GUI do SnapManager abertas, todas as sessões de GUI do Open SnapManager não responderão.


*Limitações relacionadas ao SnapMirror e ao SnapVault*

* O script de pós-processamento do SnapVault não é suportado se você estiver usando o Data ONTAP operando no modo 7D.
* Se você estiver usando o ONTAP, não será possível executar SnapRestore baseado em volume (VBSR) nos backups criados nos volumes que têm relações SnapMirror estabelecidas.
+
Isso ocorre por causa de uma limitação de ONTAP, que não permite que você quebre o relacionamento ao fazer um VBSR. No entanto, você pode executar um VBSR no último ou mais recente backup criado apenas quando os volumes tiverem relações SnapVault estabelecidas.

* Se você estiver usando o Data ONTAP operando no modo 7 e quiser executar um VBSR nos backups criados nos volumes que têm relações SnapMirror estabelecidas, você pode definir a `override-vbsr-snapmirror-check` opção como `*ON*` no SnapDrive para UNIX.
+
A documentação do SnapDrive tem mais informações sobre isso.

* Em alguns cenários, não é possível excluir o último backup associado à primeira cópia Snapshot quando o volume tiver uma relação SnapVault estabelecida.
+
Você pode excluir o backup somente quando você quebrar o relacionamento. Esse problema ocorre devido a uma restrição do ONTAP com cópias Snapshot básicas. Em uma relação do SnapMirror, a cópia Snapshot base é criada pelo mecanismo SnapMirror e, em uma relação do SnapVault, a cópia Snapshot base é o backup criado usando o SnapManager. Para cada atualização, a cópia Snapshot base aponta para o backup mais recente criado usando o SnapManager.



*Limitações relacionadas aos bancos de dados do Data Guard Standby*

* O SnapManager não suporta bancos de dados em espera de proteção lógica de dados.
* O SnapManager não suporta bancos de dados em espera do ative Data Guard.
* O SnapManager não permite backups online de bancos de dados em espera do Data Guard.
* O SnapManager não permite backups parciais de bancos de dados em espera do Data Guard.
* O SnapManager não permite a restauração de bancos de dados em espera do Data Guard.
* O SnapManager não permite a eliminação de ficheiros de registo de arquivo para bases de dados em espera do Data Guard.
* O SnapManager não oferece suporte ao Data Guard Broker.


*Informações relacionadas*

http://mysupport.netapp.com/["Documentação no site de suporte da NetApp"^]
