---
permalink: unix-administration/concept-general-layout-and-configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, help, avoid, issue, relate, disk, group, file, type, tablespace 
summary: Conhecer os layouts gerais de banco de dados recomendados e as configurações de armazenamento pode ajudá-lo a evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela. 
---
= Layouts gerais de banco de dados recomendados e configurações de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conhecer os layouts gerais de banco de dados recomendados e as configurações de armazenamento pode ajudá-lo a evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela.

* Não inclua arquivos de mais de um tipo de sistema de arquivos SAN ou gerenciador de volumes em seu banco de dados.
+
Todos os arquivos que compõem um banco de dados devem residir no mesmo tipo de sistema de arquivos.

* O SnapManager requer vários tamanhos de bloco de 4K KB.
* Inclua o identificador do sistema de banco de dados no `oratab` arquivo.
+
Inclua uma entrada no `oratab` arquivo para cada banco de dados a ser gerenciado. O SnapManager depende do `oratab` arquivo para determinar qual casa do Oracle usar.



Se você quiser aproveitar a nova restauração baseada em volume ou a restauração completa do grupo de discos, considere as seguintes diretrizes relacionadas aos sistemas de arquivos e grupos de discos:

* Um grupo de discos contendo arquivos de dados não pode conter outros tipos de arquivos.
* O número de unidade lógica (LUN) para o grupo de discos de arquivo de dados deve ser o único objeto no volume de armazenamento.


A seguir estão algumas diretrizes para separação de volumes:

* Os arquivos de dados para apenas um banco de dados devem estar no volume.
* Você deve usar volumes separados para cada uma das seguintes classificações de arquivos: Binários de banco de dados, arquivos de dados, arquivos de log refazer on-line, arquivos de log refazer arquivados e arquivos de controle.
* Você não precisa criar um volume separado para arquivos temporários de banco de dados porque o SnapManager não faz backup de arquivos temporários de banco de dados.


O SAP usa um layout padrão para instalações de banco de dados Oracle. Nesse layout, o SAP coloca cópias do arquivo de controle Oracle em `E:\oracle\SID\origlogA, E:\oracle\SID\origlogB`, e `E:\oracle\SID\sapdata1 file systems`.

O arquivo de controle no sistema de arquivos sapdata1 entra em conflito com os requisitos do SnapManager para separar os arquivos de controle e dados em volumes separados e deve ser ajustado para permitir a capacidade de restauração rápida.


NOTE: Como os backups BR*Tools incluem os perfis Oracle e SAP localizados no subdiretório dbs da instalação Oracle, a instalação Oracle deve estar localizada no armazenamento.

No caso de uma nova instalação, você pode modificar a localização dos arquivos de controle usando SAPINST e mover o arquivo de controle normalmente colocado no sistema de arquivos sapdata1 para um sistema de arquivos que não reside no mesmo volume que os arquivos de dados. (SAPINST é a ferramenta que a SAP fornece para a instalação de sistemas SAP.)

No entanto, no caso de um sistema que já tenha sido instalado, você deve mover o arquivo de controle do sistema de arquivos para permitir restauração rápida usando o SnapManager. Você pode fazer isso criando um novo sistema de arquivos em um volume que não contém arquivos de dados, movendo o arquivo de controle para esse sistema de arquivos e, em seguida, criando um link simbólico do sistema de arquivos anterior para o diretório do novo sistema de arquivos. É necessário parar o SAP e o banco de dados Oracle ao mover o arquivo de controle para evitar erros de banco de dados.

Antes de fazer quaisquer modificações, a listagem dos arquivos no diretório sapdata1 que contém o arquivo de controle pode ser assim:

[listing]
----
hostname:/
#  ls -l /oracle/SID/sapdata1/cntrl
-rw-r----- 1 orasid  dba  9388032 Jun 19 01:51 cntrlSID.dbf
----
Após a modificação, a listagem pode ser assim:

[listing]
----
hostname:/
# ls -sl /oracle/SID/sapdata1
0 lrwxrwxrwx 1 root root 19 2008-08-06 14:55 cntrl -> /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:57 data01.dbf

# ls -sl /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:56 cntrlSID.dbf
----