---
permalink: unix-administration/concept-restore-preview-plans.html 
sidebar: sidebar 
keywords: snapmanager, restore, plan, before, after, operation, preview, review, analyze 
summary: O SnapManager fornece planos de restauração antes e depois que uma operação de restauração for concluída. Os planos de restauração são usados para visualizar, revisar e analisar a respeito de diferentes métodos de restauração. 
---
= Quais são os planos de visualização de restauração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager fornece planos de restauração antes e depois que uma operação de restauração for concluída. Os planos de restauração são usados para visualizar, revisar e analisar a respeito de diferentes métodos de restauração.



== Estrutura do plano de restauração

O plano de restauração consiste nas duas seções a seguir:

* Pré-visualização/Revisão: Esta seção descreve como o SnapManager restaurará (ou restaurou) cada arquivo.
* Análise: Esta seção descreve por que alguns mecanismos de restauração não foram usados durante a operação de restauração.




== A secção Pré-visualização/Revisão

Esta seção mostra como cada arquivo será ou foi restaurado. Quando você visualiza o plano de restauração antes de uma operação de restauração, ele é chamado de visualização. Quando você a visualiza depois que uma operação de restauração é concluída, ela é chamada de revisão.

O exemplo de visualização a seguir mostra que os arquivos são restaurados usando a restauração rápida baseada em volume, a restauração do sistema de arquivos no lado do armazenamento e os métodos de restauração do sistema no lado do armazenamento. Para determinar por que todos os arquivos não seriam restaurados usando o mesmo método de restauração, consulte a seção análise.

[listing]
----
Preview:
The following files will be restored completely via: fast restore
+DG1/rac6/users.dbf

The following files will be restored completely via: storage side file system restore
+DG2/rac6/sysaux.dbf
+DG2/rac6/system.dbf
The following files will be restored completely via: storage side system restore
+DG2/rac6/undotbs1.dbf
+DG2/rac6/undotbs2.dbf
----
Cada método de restauração tem uma subseção que contém informações sobre os arquivos que podem ser restaurados usando esse método de restauração. As subseções são ordenadas de acordo com níveis decrescentes de eficiência do método de armazenamento. No exemplo acima, o método de restauração rápida é mais eficiente do que o método de restauração do sistema de arquivos de armazenamento e assim é exibido primeiro.

É possível que um arquivo seja restaurado por vários métodos de restauração. Vários métodos de restauração são usados quando os LUNs (números de unidade lógica) subjacentes usados para um sistema de arquivos são distribuídos entre diferentes volumes do sistema de storage e alguns volumes são elegíveis para restauração de volume, enquanto outros não. Se forem utilizados vários métodos de restauro para restaurar o mesmo ficheiro, a secção de pré-visualização será semelhante à seguinte:

[listing]
----
The following files will be restored via a combination of:
[fast restore, storage side file system restore. storage side system restore]
----


== A secção análise

A seção análise apresenta as razões pelas quais alguns mecanismos de restauração não serão ou não foram usados. Você pode usar essas informações para determinar o que é necessário para habilitar mecanismos de restauração mais eficientes.

O exemplo a seguir mostra uma seção de análise:

[listing]
----
Analysis:

The following reasons prevent certain files from being
restored completely via: fast restore
   * LUNs present in snapshot of volume fas960:
        /vol/rac_6_asm_disks may not be consistent when reverted:
        [fas960:/vol/rac6_asm_disks/DG4D1.lun]
     Mapped LUNs in volume fas960:/vol/rac_6_asm_disks
        not part of the restore scope will be reverted: [DG4D1.lun]

Files to restore:
     +DG2/rac6/sysaux.dbf
     +DG2/rac6/system.dbf
     +DG2/rac6/undotbs1.dbf
     +DG2/rac6/undotbs2.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
No exemplo, a primeira falha é sobrerrigível usando `-fast -override` a partir da interface de linha de comando (CLI), ou selecionando *Substituir* na interface gráfica do usuário (GUI). A segunda falha sobre LUNs mapeados no volume é obrigatória e não pode ser substituída.

Você pode resolver verificações fazendo o seguinte:

* Para resolver uma falha de verificação obrigatória, altere o ambiente para que a verificação passe.
* Para resolver uma falha de verificação sobrecarregável, você pode alterar o ambiente ou substituir a verificação.
+
No entanto, você deve ter cuidado, porque a substituição da verificação pode resultar em consequências indesejadas.


