---
permalink: unix-administration/concept-cloning-methods.html 
sidebar: sidebar 
keywords: clone, database, crate, operation, cloning, method 
summary: Você pode clonar um banco de dados usando um de dois métodos. O método escolhido afeta a operação de criação de clone. 
---
= Métodos de clonagem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode clonar um banco de dados usando um de dois métodos. O método escolhido afeta a `clone create` operação.

A tabela a seguir descreve os métodos de clonagem e seu efeito sobre a `clone create` operação e `-reserve` sua opção. Um LUN pode ser clonado usando qualquer um dos métodos.

[cols="1a,1a,2a"]
|===
| Método de clonagem | Descrição | clone create -reserve 


 a| 
Clonagem de LUN
 a| 
Um novo LUN clone é criado dentro do mesmo volume.
 a| 
Quando `-reserve` para um LUN está definido como `yes`, o espaço é reservado para o tamanho total do LUN dentro do volume.



 a| 
Clonagem de volume
 a| 
Um novo FlexClone é criado e o clone LUN existe dentro do novo volume de clone. Utiliza a tecnologia FlexClone.
 a| 
Quando `-reserve` para um volume é definido como `yes`, o espaço é reservado para o tamanho total do volume dentro do agregado.

|===