---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 'Você pode gerenciar a segurança no SnapManager aplicando autenticação de usuário e controle de acesso baseado em funções (RBAC). O método de autenticação de usuário permite acessar recursos como repositórios, hosts e perfis. O RBAC permite restringir as operações que o SnapManager pode executar em relação aos volumes e LUNs que contêm os arquivos de dados em seu banco de dados.' 
---
= Gerenciamento de segurança e credenciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar a segurança no SnapManager aplicando autenticação de usuário e controle de acesso baseado em função (RBAC). O método de autenticação de usuário permite acessar recursos como repositórios, hosts e perfis. O RBAC permite restringir as operações que o SnapManager pode executar em relação aos volumes e LUNs que contêm os arquivos de dados em seu banco de dados.

Quando você executa uma operação usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI), o SnapManager recupera as credenciais definidas para repositórios e perfis. O SnapManager salva credenciais de instalações anteriores.

O repositório e os perfis podem ser protegidos com uma senha. Uma credencial é a senha configurada para o usuário para um objeto e a senha não está configurada no próprio objeto.

Você pode gerenciar autenticação e credenciais executando as seguintes tarefas:

* Gerencie a autenticação do usuário por meio de prompts de senha em operações ou usando o `smsap credential set` comando.
+
Defina credenciais para um repositório, host ou perfil.

* Exibir as credenciais que regem os recursos aos quais você tem acesso.
* Limpe as credenciais de um usuário para todos os recursos (hosts, repositórios e perfis).
* Exclua as credenciais de um usuário para recursos individuais (hosts, repositórios e perfis).


Você pode gerenciar o acesso baseado em funções executando as seguintes tarefas:

* Ative o RBAC para SnapManager usando o SnapDrive.
* Atribua usuários a funções e defina recursos de função usando o console do Operations Manager.
* Opcionalmente, ative o SnapManager para armazenar senhas criptografadas editando o `smsap.config file`.


Se o Protection Manager estiver instalado, o acesso aos recursos será afetado das seguintes maneiras:

* Se o Gerenciador de proteção estiver instalado, quando você criar um perfil de banco de dados, o SnapManager criará um conjunto de dados e preencherá o conjunto de dados com os volumes que contêm os arquivos do banco de dados.
+
Após uma operação de backup, o SnapManager mantém o conteúdo do conjunto de dados sincronizado com os arquivos do banco de dados.

* Se o Gerenciador de proteção não estiver instalado, o SnapManager não poderá criar um conjunto de dados e não poderá definir proteção em perfis.

