---
permalink: unix-administration/reference-the-smo-notification-removesummarynotification-command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, profile, repository, database, smsap, remove-summary-notification 
summary: Este comando desativa a notificação de resumo para vários perfis em um banco de dados de repositório. 
---
= O comando smsap notification remove-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando desativa a notificação de resumo para vários perfis em um banco de dados de repositório.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification
-repository
-dbname _repo_service_name_
-port _repo_port_
-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]
----


== Parâmetros

* `*-repository*`
+
As opções a seguir `-repository` especificam os detalhes do banco de dados para o repositório.

* `*-port _repo_port_*`
+
Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.

* `*-dbname _repo_service_name_*`
+
Especifica o nome do banco de dados que armazena o repositório. Use o nome global ou o SID.

* `*-host _repo_host_*`
+
Especifica o nome ou endereço IP do computador host no qual o banco de dados do repositório é executado.

* `*-login _repo_username_*`
+
Especifica o nome de login necessário para acessar o banco de dados que armazena o repositório.

* `*-quiet*`
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* `*-verbose*`
+
Exibe mensagens de erro, aviso e informativas no console.



'''
O exemplo a seguir desativa a notificação de resumo para vários perfis em um banco de dados de repositório.

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5]
----
'''