---
permalink: unix-administration/reference-the-smosmsapclone-template-command.html 
sidebar: sidebar 
keywords: command, create, clone, specification, template, smsap 
summary: Este comando permite criar um modelo de especificação de clone. 
---
= O comando smsap clone template
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite criar um modelo de especificação de clone.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[smsap clone template
-profile _name_
[-backup-id _guid_  | -backup-label _backup_name_\]
[-quiet | -verbose]]
----


== Parâmetros

* ``*-profile _name_*``
+
Especifica o banco de dados do qual você deseja criar uma especificação de clone. O perfil contém o identificador da base de dados e outras informações da base de dados.

* ``*-backup-id _guid_*``
+
Cria uma especificação de clone a partir do backup com o GUID especificado. O GUID é gerado pelo SnapManager quando cria uma cópia de segurança. Use o comando smsap backup list para exibir o GUID para cada backup.

* ``*-backup-label _backup_label_name_*``
+
Cria uma especificação de clone a partir do backup com a etiqueta de backup especificada.

* ``*-quiet*``
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* ``*-verbose*``
+
Exibe mensagens de erro, aviso e informativas no console.



'''


== Exemplo de comando

O exemplo a seguir cria um modelo de especificação clone do backup com o rótulo full_backup_sales_May. Uma vez que o comando do modelo de clone smsap seja concluído, o modelo de especificação de clone será concluído.

[listing]
----
smsap clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
'''