---
permalink: unix-administration/reference-the-smosmsap-notification-set-command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smsap 
summary: Você pode usar o comando Notification set para configurar o servidor de e-mail. 
---
= O comando smsap notification set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `notification set` comando para configurar o servidor de e-mail.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[smsap notification set
-sender-email _email_address_
-mailhost _mailhost_
-mailport _mailport_
[-authentication
-username _username_
-password _password_]]
pass:quotes[-repository
-dbname _repo_service_name_
-port _repo_port_]]
pass:quotes[-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]

----


== Parâmetros

* `*-sender-email _email_address_*`
+
Especifica o endereço de e-mail do remetente a partir do qual os alertas de e-mail são enviados. No SnapManager 3,2 para SAP, você pode incluir um hífen (-) ao especificar o nome de domínio do endereço de e-mail. Por exemplo, você pode especificar o endereço de e-mail do remetente como -sender-email07lbfmdatacenter@continental-corporation.com.

* `*-mailhost _mailhost_*`
+
Especifica o nome ou endereço IP do servidor host que manipula notificações de e-mail.

* `*-mailport _mailport_*`
+
Especifica o número da porta do servidor de correio.

* `*-authentication -username _username_ -password _password_*`
+
Especifica os detalhes de autenticação para o endereço de e-mail. Tem de especificar o nome de utilizador e a palavra-passe.

* `*-repository*`
+
Especifica os detalhes do banco de dados do repositório.

* `*-port _repo_port_*`
+
Especifica o número da porta TCP (Transmission Control Protocol) usada para acessar o banco de dados do repositório.

* `*-dbname _repo_service_name_*`
+
Especifica o nome do banco de dados do repositório. Você pode usar o nome global ou o identificador do sistema.

* `*-host _repo_host_*`
+
Especifica o nome ou endereço IP do host onde reside o banco de dados do repositório.

* `*-login*`
+
Especifica os detalhes de login do repositório. Isso é opcional. Se não for especificado, o SnapManager padrão será o modo de conexão de autenticação do sistema operacional.

* `*-username _repo_username_*`
+
Especifica o nome de usuário necessário para acessar o banco de dados do repositório.

* `*-quiet*`
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* `*-verbose*`
+
Exibe mensagens de erro, aviso e informativas no console.



'''


== Exemplo

O exemplo a seguir configura o servidor de e-mail:

[listing]
----
smsap notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMSAPREPO -host hotspur
-login -username grabal21 -verbose
----
'''