---
permalink: unix-administration/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credentials, secure, resource, smsap 
summary: Este comando exclui as credenciais do usuário para um determinado recurso protegido. 
---
= O comando smsap Credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando exclui as credenciais do usuário para um determinado recurso protegido.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== Parâmetros

* `*-host _hostname_*`
+
Especifica o nome do servidor host no qual o SnapManager está sendo executado.

+
O `-host` parâmetro inclui as seguintes opções:

+
** `-name _host_name_`: Especifica o nome do host para o qual você excluirá a senha.
** `-username _user_name_`: Especifica o nome de usuário no host.


* `*-repository -dbname*`
+
Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.

+
O `-repository` parâmetro inclui as seguintes opções:

+
** `-dbname _repo_service_name_`: Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.
** `-host _repo_host_`: Especifica o nome ou endereço IP do servidor host no qual o banco de dados do repositório é executado.
** `-login-username _repo_username_`: Especifica o nome de usuário necessário para acessar o banco de dados que armazena o repositório.
** `-port _repo_port_`: Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.


* `*-profile -name _profile_name_*`
+
Especifica o perfil ao qual o banco de dados está associado.

+
O `-profile` parâmetro inclui a seguinte opção:

+
** `-name _profilename_`: Especifica o nome do perfil para o qual você excluirá a senha.


* `*-quiet*`
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* `*-verbose*`
+
Exibe mensagens de erro, aviso e informativas no console.



'''


== Exemplo de comando

Este exemplo exclui as credenciais do perfil.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Este exemplo exclui as credenciais do repositório.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Este exemplo exclui as credenciais do host.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
'''