---
permalink: unix-administration/reference-the-smosmsapclone-show-command.html 
sidebar: sidebar 
keywords: run, clone, show, command, display, information, database, profile, smsap 
summary: Você pode executar o comando clone show para exibir informações sobre os clones do banco de dados para o perfil especificado. 
---
= O comando smsap clone show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o `clone show` comando para exibir informações sobre os clones do banco de dados para o perfil especificado.



== Sintaxe

[listing, subs="+macros"]
----
pass:quotes[smsap clone show
-profile _profile_name_
[-id  _guid_ | -label _clone_name_\]
[-quiet | -verbose\]]
----


== Parâmetros

* ``*-profile _profile_name_*``
+
Especifica a lista de clones associados ao perfil. O perfil contém o identificador da base de dados e outras informações da base de dados.

* ``*-id guid*``
+
Mostra informações sobre o clone com o GUID especificado. O GUID é gerado pelo SnapManager quando você cria um clone. Você pode usar o `smsap clone show` comando para exibir o GUID para cada clone.

* ``*-label _label_name_*``
+
Mostra informações sobre o clone com o rótulo especificado.

* ``*-quiet*``
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* ``*-verbose*``
+
Exibe mensagens de erro, aviso e informativas no console.



'''


== Exemplo

O exemplo a seguir exibe informações sobre o clone:

[listing]
----
smsap clone show -profile SALES1 -label full_backup_sales_May -verbose
----
'''
'''
A saída a seguir mostra informações sobre um clone de um backup no storage primário:

[listing]
----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: /mnt/ssys1/data_clone
File: /mnt/ssys1/data_clone/hsdb/sysaux01.dbf
File: /mnt/ssys1/data_clone/hsdb/undotbs01.dbf
File: /mnt/ssys1/data_clone/hsdb/users01.dbf
File: /mnt/ssys1/data_clone/hsdb/system01.dbf
File: /mnt/ssys1/data_clone/hsdb/undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----
'''
'''
A saída a seguir mostra informações sobre um clone de um backup protegido no storage secundário:

[listing]
----
clone show -label clone_CLSTEST -profile
TEST_USER_NFSTEST_DIRMAC
Clone id:8abc01ec16514aec0116514af52f0001
Clone status: SUCCESS
Clone SID: CLSTEST
Clone label: clone_CLSTEST
Clone comment:comment_for_clone_CLSTEST
Clone start time: 2007-11-18 00:46:10
Clone end time: 2007-11-18 00:47:54
Clone host: dirmac
Filesystem: /ant/fish/bt_dirmac_nfs_clone
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/sysaux01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/system01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/undotbs01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/users01.dbf
Backup id: 8abc01ec16514883011651488b580001
Backup label:full_backup
Backup SID: NFSTEST
Backup comment:
Backup start time: 2007-11-18 00:43:32
Backup end time: 2007-11-18 00:45:30
Backup host: dirmac
Storage System: fish (Secondary storage)
Volume: bt_dirmac_nfs
Snapshot:smsap_user_nfstest_b_nfstest_f_c_1_8abc01ec16511d6a0116511d73590001_0
File: /ant/fish/bt_dirmac_nfs/archlogs/1_14_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/sysaux01.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/undotbs01.dbf
File: /ant/fish/bt_dirmac_nfs/archlogs/1_13_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/archlogs_2/1_16_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/users01.dbf
File: /ant/fish/bt_dirmac_nfs/controlfiles/SMSAPBakCtl_1195361899651_2
File: /ant/fish/bt_dirmac_nfs/datafiles/system01.dbf
----
'''