---
permalink: unix-administration/task-add-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command 
summary: Depois de configurar uma notificação de e-mail de resumo para o banco de dados do repositório, você pode adicionar um novo perfil à notificação de resumo usando o comando de notificação de resumo. 
---
= Adicione um novo perfil às notificações de e-mail resumidas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de configurar uma notificação de e-mail de resumo para o banco de dados do repositório, você pode adicionar um novo perfil à notificação de resumo usando o comando de notificação de resumo.

.Passo
. Introduza o seguinte comando:
+
`*smsap profile create -profile _profile_name_ [-profile-password _profile_password_] -repository-dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_-port _db_port_] [-rman {-controlfile | \{-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count_n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-summary-notification]*`

+
Outras opções para este comando são as seguintes:

+
``[-force]``

+
``[-quiet | -verbose]``


