---
permalink: unix-administration/task-protect-archive-log-backups.html 
sidebar: sidebar 
keywords: create, creating, profile, enable, protection, archive, log, backup, policy, protect 
summary: Ao criar perfis, você pode ativar a proteção para os backups de log de arquivamento com base na política de proteção de log de arquivamento. 
---
= Proteger backups de log de arquivamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar perfis, você pode ativar a proteção para os backups de log de arquivamento com base na política de proteção de log de arquivamento.

.Passo
. Introduza o seguinte comando:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_ | -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
[cols="2a,5a"]
|===
| Se... | Então... 


 a| 
*Você deseja fazer backup dos backups de log de arquivamento separadamente e proteger os arquivos de log de arquivamento*
 a| 
Especifique as seguintes opções:

** `-separate-archivelog-backups` permite separar os ficheiros de registo de arquivo dos ficheiros de dados.
** `-protect` atribui uma política de proteção separada para os backups de log de arquivamento.
** `-protection-policy` atribui a política de proteção para os backups de log de arquivamento.


|===

