---
permalink: unix-administration/task-preview-backup-restore-information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, snapmanager, sap, successful 
summary: Você pode visualizar informações sobre um processo de restauração de backup antes que ele ocorra para ver informações sobre a elegibilidade de restauração que o SnapManager para SAP encontrou no seu backup. O SnapManager analisa os dados do seu backup para determinar se o processo de restauração pode ser concluído com sucesso. 
---
= Visualizar informações de restauração de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações sobre um processo de restauração de backup antes que ele ocorra para ver informações sobre a elegibilidade de restauração que o SnapManager para SAP encontrou no seu backup. O SnapManager analisa os dados do seu backup para determinar se o processo de restauração pode ser concluído com sucesso.

*Sobre esta tarefa*

A visualização de restauração fornece as seguintes informações:

* Qual mecanismo de restauração (restauração rápida, restauração do sistema de arquivos no lado do armazenamento, restauração de arquivos no lado do armazenamento ou restauração de cópia de arquivos no lado do host) pode ser usado para restaurar cada arquivo.
* Por que mecanismos mais eficientes não foram usados para restaurar cada arquivo, quando você especifica a `-verbose` opção.


Se você especificar a `-preview` opção no `backup restore` comando, o SnapManager não restaura nada, mas lista os arquivos a serem restaurados e indica como eles serão restaurados.


NOTE: Você pode visualizar todos os tipos de mecanismos de restauração. A visualização mostra informações sobre até 20 arquivos.

.Passos
. Introduza o seguinte comando:
+
`*smsap backup restore -profile _profile_name_ -label _label_ -complete -preview -verbose*`

+
*Exemplo*

+
Por exemplo, digite:

+
[listing]
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
O exemplo a seguir mostra alguns arquivos sendo restaurados usando o processo de restauração de cópia de arquivo do lado do host e também explica por que alguns arquivos não podem ser restaurados usando a opção de restauração rápida. Se você especificar a `-verbose` opção, o SnapManager exibirá uma seção de visualização e uma seção de análise que explica por que cada arquivo não pode ser restaurado através do processo de restauração rápida.

+
[listing]
----
PREVIEW:
The following files will be restored via host side file copy restore:
+DG2/sid/datafile10.dbf
+DG2/sid/datafile11.dbf

ANALYSIS:
The following reasons prevent certain files from being restored via fast restore:
Reasons:
 Newer snapshots of /vol/volume2 have volume clones: SNAP_1
*Newer backups will be freed: nightly2, nightly3
Files to Restore:
/mnt/systemB/volume2/system.dbf
/mnt/systemB/volume2/users.dbf
/mnt/systemB/volume2/sysaux.dbf
/mnt/systemB/volume2/datafile04.dbf
/mnt/systemB/volume2/datafile05.dbf

The following reasons prevent certain files from being restored via fast restore:
Reasons:
* Newer snapshots of /vol/adm_disks will be lost: ADM_SNAP_5
* Luns present which were created after snapshot SNAP_0 was created: /vol/adm_disks/disk5.lun
* Files not part of the restore scope will be reverted in file system: +DG2

Files Not in Restore Scope: +DG2/someothersid/data01.dbf
+DG2/someothersid/data02.dbf
Files to Restore:
+DG2/sid/datafile08.dbf +DG2/sid/datafile09.dbf
+DG2/sid/datafile10.dbf +DG2/sid/datafile11.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
. Reveja os motivos pelos quais outros processos de restauração não podem ser usados.
. Inicie a operação de restauração sem a `-preview` opção, se apenas forem exibidas razões que sejam sobrepostas.
+
Você ainda pode substituir verificações não obrigatórias.


