---
permalink: unix-administration/task-split-a-clone-on-a-primary-or-secondary-storage.html 
sidebar: sidebar 
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free 
summary: Você pode usar o comando clone split para dividir o clone. Após a conclusão da divisão de clones, os metadados do clone são removidos do banco de dados do repositório e o backup associado ao clone pode ser excluído ou liberado. 
---
= Dividir um clone em storage primário ou secundário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `clone split` comando para dividir o clone. Após a conclusão da divisão de clones, os metadados do clone são removidos do banco de dados do repositório e o backup associado ao clone pode ser excluído ou liberado.

*Sobre esta tarefa*

O novo perfil criado após a operação de divisão bem-sucedida é usado para gerenciar o clone dividido. O novo perfil será como qualquer outro perfil existente no SnapManager. Você pode usar esse perfil para executar operações de backup, restauração e clone.

Além disso, você também pode configurar a notificação por e-mail para o novo perfil. Isso permite que o administrador do banco de dados seja notificado sobre o status da operação do banco de dados realizada usando o perfil.


NOTE: O SnapManager suporta a operação de divisão quando realizada apenas em um FlexClone.

Se a operação de divisão falhar, uma mensagem de erro apropriada com o motivo da falha é exibida. O estado de várias operações também é apresentado no registo de operações. Por exemplo:

[listing]
----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----
Opcionalmente, você pode coletar os arquivos de despejo após uma operação de divisão de clones bem-sucedida ou com falha.


NOTE: Depois de inserir o `clone split` comando, você não deve parar o servidor SnapManager até que a operação de divisão de clones tenha sido iniciada.


NOTE: O SnapManager gera o perfil mesmo que você não forneça nenhum valor para a conta Oracle (osaccount e osgroup).

.Passo
. Introduza o seguinte comando:
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`


