---
permalink: unix-administration/task-schedule-archive-log-file-pruning.html 
sidebar: sidebar 
keywords: create, backup, schedule, pruning, prune, archive, log, file, scheduling 
summary: Quando você cria um backup, você pode agendar a eliminação de arquivos de log de arquivamento para ocorrer em um horário especificado. 
---
= Agendar a eliminação do ficheiro de registo de arquivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você cria um backup, você pode agendar a eliminação de arquivos de log de arquivamento para ocorrer em um horário especificado.

*Sobre esta tarefa*

O SnapManager permite que você pode os arquivos de log de arquivamento periodicamente do sistema de arquivos ativo.

.Passo
. Introduza o seguinte comando:
+
`*smsap schedule create -profile _profile_name_ {[-full {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-files _files_ [_files_]] | [-tablespaces _-tablespaces_ [_-tablespaces_]] {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-comment _comment_] [-protect | -protectnow | -noprotect] [-backup-dest _path1_ [,[_path2_]] [-exclude-dest _path1_ [_,path2_]] [-prunelogs{-all | -untilSCN _untilSCN_ | -before {-date _yyyy-MM-dd HH:mm:ss_ | -months _months_ | -weeks _weeks_ | -days _days_ | -hours _hours_}} -prune-dest _prune_dest1,,prune_dest2_] -schedule-name _schedule_name_ [-schedule-commentschedule_comment] -interval {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-onetimeonly_} -cronstring _cronstring_ -start-time {_start-time start_time <yyyy-MM-dd HH:mm>_} -runasuser _-runasuser_ [-force] [-quiet | -verbose]*`

+
[cols="2a,4a"]
|===
| Se você quiser... | Então... 


 a| 
*Agendar a eliminação de arquivos de log de arquivo*
 a| 
Especifique as seguintes opções:

** `-prunelogs` para agendar a eliminação dos ficheiros de registo de arquivo
** `-prune-dest` para definir ficheiros de registo de arquivo a partir dos destinos de registo de arquivo




 a| 
*Inclua um nome para a programação*
 a| 
Especifique a `-schedule-name` opção.



 a| 
*Agendar a eliminação de ficheiros de registo de arquivo no intervalo de tempo específico*
 a| 
Especifique a `interval` opção e indique se os arquivos de log de arquivo devem ser podados com base nas seguintes classes de intervalo:

** `-hourly`
** `-daily`
** `-weekly`
** `-monthly`
** `-onetimeonly`




 a| 
*Adicione um comentário sobre a operação de programação*
 a| 
Especifique a `-schedule-comment` opção seguida da string de descrição.



 a| 
*Especifique a hora de início da operação de programação*
 a| 
Especifique a `-start-time` opção no formato aaaa-mm-dd hh:mm.

|===

