---
permalink: unix-installation-cmode/task-create-an-oracle-user-for-the-repository-database-instance.html 
sidebar: sidebar 
keywords: oracle, user, require, log, access, repository, database, instance, create, user, connect, resource, privilege, create 
summary: Um usuário Oracle é necessário para fazer login e acessar a instância do banco de dados do repositório. Você deve criar esse usuário com o Connect e o Resource Privileges. 
---
= Crie um usuário Oracle para a instância de banco de dados do repositório
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um usuário Oracle é necessário para fazer login e acessar a instância do banco de dados do repositório. Você deve criar esse usuário com _connect_ e _resource_ Privileges.

.Passos
. Faça login no SQL *Plus: `sqlplus '/ as sysdba'`
. Crie um novo usuário e atribua uma senha de administrador a esse usuário: `*create useruser_name identified by admin_password default tablespace tablespace_name quota unlimited on tablespace_name;*`
+
** `user_name` é o nome do usuário que você está criando para o banco de dados do repositório.
** `admin_password` é a palavra-passe que pretende atribuir ao utilizador.
** `tablespace_name` é o nome do espaço de tabela criado para o banco de dados do repositório.


. Atribua _connect_ e _resource_ Privileges ao novo usuário Oracle: `*grant connect, resource to user_name;*`

